"use client";

import { useEffect } from "react";
import type { ProductRow } from "./contract";
import { encodeProductIdentity, type InsightsContext } from "@/lib/netshop/insights-contract";
import type { NetshopColumnProps } from "../shared/module-slots";
import { InsightListPagination, InsightReadState } from "../shared/components";
import type { ProductInsightsResponse } from "./contract";
import { CompareCell, MetricCell, MissingSource, ProductPicture, ProductsDerivedMetric, ProductsMetric, ProductsPanel } from "./ProductsPrimitives";
import { ProductsBars, ProductsScatter } from "./ProductsCharts";
import { ProductsCoverage } from "./ProductsCoverage";
import { productPrincipalKey, productsQuery, readInsights, useProductRead } from "./ProductsRead";
import { productSortOptions, type ProductsUiChange, type ProductsUiState } from "./ui-state";

export function ProductRows({ rows, columns, previous, yearAgo, onSelect, showDelta = false }: { rows: ProductRow[]; showDelta?: boolean; columns: ProductsUiState["columns"]; previous: boolean; yearAgo: boolean; onSelect: (row: ProductRow) => void }) {
  return <div className="np-table-wrap"><table className="np-table"><thead><tr><th>图片 / 商品名称 / 身份</th><th className="np-number">平台销售额（元）</th><th className="np-number">销量（件）</th>{columns.traffic && <><th className="np-number">访客累计</th><th className="np-number">转化率</th><th className="np-number">加购率</th></>}{columns.comparison && yearAgo && <th className="np-number">同比（销售额）</th>}{columns.comparison && previous && <><th className="np-number">环比基期销售额（元）</th><th className="np-number">环比（销售额）</th></>}{showDelta && <th className="np-number">销售额变化贡献（元）</th>}{columns.association && <th>推广 / ERP关联</th>}{columns.coverage && <th>覆盖状态</th>}<th>操作</th></tr></thead><tbody>{rows.map(row => <tr key={encodeProductIdentity(row.identity)}><td><div className="np-product-cell"><ProductPicture title={row.title} url={row.imageUrl} /><div><button type="button" className="np-link" onClick={() => onSelect(row)}>{row.title}</button><small>{row.identity.platform} · {row.identity.shopName}</small><small>{row.identity.dimension.toUpperCase()} {row.identity.id}</small><small>{row.category || "类目未提供"}</small></div></div></td><td className="np-number"><MetricCell metric={row.metrics.payment} /></td><td className="np-number"><MetricCell metric={row.metrics.quantity} /></td>{columns.traffic && <><td className="np-number"><MetricCell metric={row.metrics.visitors} /></td><td className="np-number"><MetricCell metric={row.metrics.conversion} /></td><td className="np-number"><MetricCell metric={row.metrics.addCartRate} /></td></>}{columns.comparison && yearAgo && <td className="np-number"><CompareCell comparison={row.comparisons.payment.yearAgo} /></td>}{columns.comparison && previous && <><td className="np-number"><MetricCell metric={row.baselineMetrics.previous.payment} /></td><td className="np-number"><CompareCell comparison={row.comparisons.payment.previous} /></td></>}{showDelta && <td className="np-number">{row.paymentDelta ? <MetricCell metric={row.paymentDelta} /> : "— · 变化金额未提供"}</td>}{columns.association && <td><span className="np-caption">进入详情核验关联</span></td>}{columns.coverage && <td><span className={`np-badge${row.metrics.payment.status === "available" ? "" : " np-warning"}`}>{row.metrics.payment.status === "available" ? "成交字段完整" : "成交字段受限"}</span></td>}<td><button type="button" onClick={() => onSelect(row)}>详情</button></td></tr>)}</tbody></table>{rows.length === 0 && <p className="np-empty">当前列表筛选没有匹配商品</p>}</div>;
}

function BaselineWarnings({ data, previous, yearAgo }: { data: ProductInsightsResponse; previous: boolean; yearAgo: boolean }) {
  return <>{(["previous", "yearAgo"] as const).map(key => (key === "previous" ? previous : yearAgo) && data.sections.baselineReads[key].state === "error" ? <p className="np-notice" role="status" key={key}>{key === "previous" ? "环比" : "同比"}来源读取失败：{data.sections.baselineReads[key].message}。本期数据仍按可靠来源展示，比较为空。</p> : null)}</>;
}
const summaryLabels = { payment: "平台销售额", quantity: "销量（件）", visitors: "访客累计", customers: "成交客户累计", conversion: "商品累计转化率", addCartRate: "加购客户率", refundPayment: "平台退款金额" } as const;
const changeLabels = { pairedCurrentPayment: "可比本期销售额", pairedPreviousPayment: "可比环比基期销售额", growthPayment: "正向增长贡献", declinePayment: "负向下降贡献", netChange: "可比净变化" } as const;
export function ProductsPerformance({ props, ui, onUi, onContextAvailable }: { props: NetshopColumnProps; ui: ProductsUiState; onUi: ProductsUiChange; onContextAvailable: (context: InsightsContext, categories: string[]) => void }) {
  const read = useProductRead(productsQuery(props, ui.sort), productPrincipalKey(props), readInsights);
  const data = read.data;
  useEffect(() => { if (data) onContextAvailable(data.context, data.sections.structure?.categories.map(row => row.categoryEvidence?.label).filter((label): label is string => typeof label === "string" && label.length > 0 && label.length <= 120) ?? []); }, [data, onContextAvailable]);
  if (!data) return <InsightReadState status={read.status} error={read.error} onRetry={read.refresh} />;
  const { sections } = data;
  const open = (row: ProductRow) => props.onDrill("products", row.identity, "overview");
  return <div className="np-stack"><BaselineWarnings data={data} previous={props.context.previous} yearAgo={props.context.yearAgo} />
    <div className="np-metrics">{sections.counts && <><ProductsMetric label="本期有数据商品" metric={sections.counts.dataProducts} /><ProductsMetric label="本期成交商品" metric={sections.counts.tradedProducts} /></>}{Object.entries(summaryLabels).map(([key, label]) => { const k = key as keyof typeof summaryLabels; return <ProductsMetric key={key} label={label} metric={sections.summary[k]} previous={sections.comparisons[k].previous} yearAgo={sections.comparisons[k].yearAgo} showPrevious={props.context.previous} showYearAgo={props.context.yearAgo} />; })}</div>
    <p className="np-note">概况来自完整平台、店铺、期间与经营类目范围；表内搜索不改变上方汇总。客户和访客是商品×日累计，SKU 与 SPU 分开统计；加购率使用加购客户累计 ÷ 访客累计。</p>
    <nav className="np-chapter-nav" aria-label="经营专题">{([["home", "经营概览"], ["growth", "贡献增长"], ["traffic", "流量效率"], ["list", "商品明细"]] as const).map(([key, label]) => <button key={key} className={ui.topic === key ? "np-active" : ""} aria-pressed={ui.topic === key} onClick={() => onUi({ ...ui, topic: key })}>{label}</button>)}</nav>
    {(ui.topic === "home" || ui.topic === "growth") && (sections.structure ? <><div className="np-two"><ProductsPanel title="成交集中度" note="完整经营筛选集合"><div className="np-metrics"><ProductsMetric label="TOP5 成交占比" metric={sections.structure.top5Share} /><ProductsMetric label="TOP10 成交占比" metric={sections.structure.top10Share} /></div><h3>TOP5 / TOP10累计贡献</h3><ProductsBars minimumScale={1} rows={[{ label: "TOP5累计贡献", metric: sections.structure.top5Share }, { label: "TOP10累计贡献", metric: sections.structure.top10Share }]} /><dl className="np-properties"><dt>持续成交商品</dt><dd><MetricCell metric={sections.structure.classification.continuous} /></dd><dt>新增成交商品</dt><dd><MetricCell metric={sections.structure.classification.newlyTraded} /></dd><dt>不再成交商品</dt><dd><MetricCell metric={sections.structure.classification.noLongerTraded} /></dd><dt>基期未知商品</dt><dd><MetricCell metric={sections.structure.classification.unknownBaseline} /></dd></dl><p className="np-note">“新增成交”只描述两期可靠记录，不代表新品。已配对 {sections.structure.qualification.paired} 个；覆盖不足 {sections.structure.qualification.incomplete} 个。</p></ProductsPanel><div className="np-stack"><ProductsPanel title="类目贡献" note={sections.structure.categoryBasis === "verified_historical" ? "有版本的历史类目归属" : "来源标签分组；不作为官方或跨平台类目字典"}><ProductsBars rows={sections.structure.categories.map(row => ({ label: row.label, metric: row.payment, share: row.share }))} /></ProductsPanel><ProductsPanel title="价格带" note={sections.structure.priceBasis === "transaction_mean" ? "按本期成交均价划分" : "按当前目录标价划分；不是历史价格"}><ProductsBars rows={sections.structure.priceBands.map(row => ({ label: row.label, metric: row.payment, share: row.share }))} /></ProductsPanel></div></div></> : <MissingSource title="贡献与结构" reason="unverified_source" />)}
    {ui.topic === "growth" && <ProductsPanel title="增长与下降贡献" note="按全集配对后的销售额变化金额排序"><p>增长、下降排行分别显示绝对销售额贡献；百分比增幅保留零、负及缺失基期说明。</p>{sections.growth.state === "ready" ? <><ProductRows showDelta rows={sections.growth.data.items} columns={ui.columns} previous={props.context.previous} yearAgo={props.context.yearAgo} onSelect={open} /><p className="np-note">完整配对集合 · 共 {sections.growth.data.pagination.total} 条。通过下方排序选择增长或下降贡献并翻页。</p></> : <p className="np-notice" role="alert">{sections.growth.message}</p>}</ProductsPanel>}
    {ui.topic === "traffic" && <ProductsPanel title="流量与成交效率" note="同源商品×日累计；不是同一批用户的旅程漏斗">{sections.efficiency ? <><div className="np-metrics">{([["pageViews", "商品浏览"], ["favorites", "收藏累计"], ["addCartCustomers", "加购客户累计"], ["addCartQuantity", "加购件数"], ["orderCustomers", "下单客户累计"], ["orderQuantity", "下单件数"], ["orderPayment", "下单金额"], ["transactionOrders", "成交订单数"], ["searchImpressions", "搜索曝光"], ["searchClicks", "搜索点击"], ["searchClickRate", "搜索点击率"], ["searchVisitors", "搜索访客"], ["searchCustomers", "搜索成交客户"]] as const).map(([key, label]) => <ProductsMetric key={key} label={label} metric={sections.efficiency!.metrics[key]} />)}{sections.efficiency.visitorValue && <ProductsDerivedMetric label="商品访客累计价值" metric={sections.efficiency.visitorValue} />}</div><ProductsScatter rows={sections.items} page={sections.pagination.page} total={sections.pagination.total} rules={sections.efficiency.rules} onSelect={open} /><p className="np-note">关注规则 {sections.efficiency.rules.id}：访客累计至少 {sections.efficiency.rules.minimumVisitors}，转化率低于 {(sections.efficiency.rules.maximumConversion * 100).toFixed(2)}%；{sections.efficiency.rules.requireComplete ? "仅纳入覆盖完整记录" : "覆盖要求见规则"}。完整扫描 {sections.efficiency.scanned} 个，命中 {sections.efficiency.qualified} 个。</p><ProductRows rows={sections.efficiency.watchlist} columns={ui.columns} previous={props.context.previous} yearAgo={props.context.yearAgo} onSelect={open} /><p className="np-caption">关注清单 {sections.efficiency.pagination.returned}/{sections.efficiency.pagination.total} 条；不是综合评分或因果诊断。</p></> : <MissingSource title="流量与关注清单" reason="unverified_source" />}</ProductsPanel>}
    <ProductsPanel title="商品经营明细" note="表内名称、ID、商家码搜索；上方汇总不随搜索变化" action={<button type="button" onClick={read.refresh}>刷新本范围</button>}>
      <div className="np-toolbar"><input aria-label="表内搜索商品名称、ID或商家码" maxLength={120} value={props.context.q} placeholder="名称、ID、商家码" onChange={event => props.onContextChange({ q: event.target.value, page: 1 })} /><select aria-label="商品明细排序" value={ui.sort} onChange={event => { onUi({ ...ui, sort: event.target.value as ProductsUiState["sort"] }, { page: 1 }); }}>{productSortOptions.map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select><select aria-label="商品明细每页条数" value={props.context.pageSize} onChange={event => props.onContextChange({ pageSize: Number(event.target.value), page: 1 })}>{[5, 10, 20, 50, 100].map(size => <option key={size} value={size}>{size}条/页</option>)}</select></div>
      <div className="np-column-picker" aria-label="商品明细列设置">{([["traffic", "访客 / 转化 / 加购"], ["comparison", "同比 / 环比"], ["association", "推广 / ERP关联"], ["coverage", "覆盖状态"]] as const).map(([key, label]) => <label key={key}><input type="checkbox" checked={ui.columns[key]} onChange={event => onUi({ ...ui, columns: { ...ui.columns, [key]: event.target.checked } })} />{label}</label>)}</div>
      <ProductRows showDelta={ui.sort === "growth_desc" || ui.sort === "decline_desc"} rows={sections.items} columns={ui.columns} previous={props.context.previous} yearAgo={props.context.yearAgo} onSelect={open} /><InsightListPagination pagination={sections.pagination} onPage={page => props.onContextChange({ page })} /><p className="np-caption">排序：{productSortOptions.find(([key]) => key === data.tableScope.sort)?.[1]} · 返回 {sections.pagination.returned}/{sections.pagination.total} 条 · 比较按相同平台、店铺、维度与ID配对。</p>
    </ProductsPanel>
    {sections.dataQuality && <ProductsPanel title="资料质量" note={`本期有日经营记录商品所对应的当前目录；陈旧规则 ${sections.dataQuality.staleAfterDays} 天；只读展示`}><div className="np-metrics">{([["missingImage", "缺少图片"], ["missingCode", "缺少编码"], ["missingCategory", "缺少类目"], ["conflict", "身份冲突"], ["stale", "陈旧资料"], ["unmapped", "未关联"]] as const).map(([key, label]) => <ProductsMetric key={key} label={key === "unmapped" && sections.dataQuality!.counts[key].reasonCode === "unverified_source" ? "ERP映射状态未核验" : label} metric={sections.dataQuality!.counts[key]} />)}</div><p className="np-note">质量项可能重叠，不相加当作异常商品总数；不会自动修改映射、改码、合并或删除商品。</p></ProductsPanel>}
    {ui.topic === "growth" && sections.structure?.changes && <ProductsPanel title="完整可比集合的变化金额" note="先在完整候选集合配对，再合计可比较对象；缺少基期的对象不被填零"><div className="np-metrics">{Object.entries(sections.structure.changes).map(([key, metric]) => <ProductsMetric key={key} label={changeLabels[key as keyof typeof changeLabels]} metric={metric} />)}</div></ProductsPanel>}
    <ProductsCoverage context={data.context} revisions={data.joinedSourceRevisions} />
  </div>;
}
