"use client";

import { useEffect } from "react";
import { type InsightsContext } from "@/lib/netshop/insights-contract";
import type { SourceSection } from "@/lib/netshop/insights-endpoints";
import type { NetshopColumnProps } from "../shared/module-slots";
import { InsightListPagination, InsightReadState } from "../shared/components";
import { productSections, type CatalogProfile, type ProductDailyData, type ProductSection, type ProductSource } from "./contract";
import { DerivedMoneyCell, MetricCell, MissingSource, ProductPicture, ProductsDerivedMetric, ProductsMetric, ProductsPanel } from "./ProductsPrimitives";
import { ProductsTrend } from "./ProductsCharts";
import { ProductsCoverage } from "./ProductsCoverage";
import { ProductRows } from "./ProductsPerformance";
import { productPrincipalKey, productsQuery, readDetail, useProductRead } from "./ProductsRead";
import { productMappingLabels, productReasonLabels, safeProductUrl, type ProductsUiChange, type ProductsUiState } from "./ui-state";

const sectionLabels: Record<ProductSection, string> = { overview: "两期成绩", trends: "分源趋势", daily: "逐日明细", catalog: "资料与快照", sku: "历史SKU贡献", promotion: "推广关联", erp: "ERP关联" };
const sourceLabels: Record<ProductSource, string> = { platform: "平台经营", promotion: "推广归因", erp: "ERP经营" };
const labels: Record<string, string> = { payment: "平台销售额", quantity: "销量（件）", visitors: "访客累计", customers: "成交客户累计", conversion: "转化率", addCartRate: "加购客户率", refundPayment: "平台退款金额", pageViews: "商品浏览", favorites: "收藏累计", addCartCustomers: "加购客户累计", addCartQuantity: "加购件数", orderCustomers: "下单客户累计", orderQuantity: "下单件数", orderPayment: "下单金额", transactionOrders: "成交订单数", searchImpressions: "搜索曝光", searchClicks: "搜索点击", searchClickRate: "搜索点击率", searchVisitors: "搜索访客", searchCustomers: "搜索成交客户", visitorValue: "商品访客价值", spend: "推广花费", attributedPayment: "广告归因成交", roas: "ROAS（倍）", clicks: "广告点击", netSales: "ERP净销售", cost: "ERP货品成本", largeMarginRate: "大毛利率", orderMargin: "订单毛利", returnAmount: "ERP退货金额", returnQuantity: "ERP退货件数" };

function SourceError<T>({ section, title }: { section: SourceSection<T>; title: string }) {
  return section.state === "error" ? <div className="np-notice" role="alert"><strong>{title}读取失败</strong><p>{section.message}</p></div> : null;
}
function CatalogProperties({ profile }: { profile: CatalogProfile }) {
  const link = safeProductUrl(profile.productUrl);
  return <><div className="np-row"><ProductPicture title={profile.title} url={profile.imageUrl} link={profile.productUrl} large /><div><h3>{profile.title}</h3><p>{profile.identity.platform} · {profile.identity.shopName} · {profile.identity.dimension.toUpperCase()} {profile.identity.id}</p>{link && <a href={link} target="_blank" rel="noreferrer">打开平台商品 ↗</a>}</div></div><dl className="np-properties"><dt>SPU / SKU ID</dt><dd>{profile.spuId || "—"} / {profile.skuId || "—"}</dd><dt>商家 / ERP编码</dt><dd>{profile.merchantCode || "— · 缺码"} / {profile.erpCode || (profile.mapping.status === "unmapped" ? "— · 未关联" : "— · 映射未核验")}</dd><dt>品牌 / 类目</dt><dd>{profile.brand || "—"} / {profile.category || "—"}</dd><dt>规格 / 状态</dt><dd>{profile.specification || "—"} / {profile.state || "未提供"}</dd><dt>当前标价</dt><dd><MetricCell metric={profile.price} /> · 快照 {profile.snapshots.price || "未提供"}</dd><dt>目录总 / 可用库存</dt><dd><MetricCell metric={profile.inventory.total} /> / <MetricCell metric={profile.inventory.available} /> · 快照 {profile.snapshots.inventory || "未提供"}</dd><dt>资料 / 图片快照</dt><dd>{profile.snapshots.master || "未提供"} / {profile.snapshots.image || "未提供"}</dd><dt>映射证据</dt><dd>{profile.mapping.status === "verified" ? "已验证关联" : profile.mapping.status === "unmapped" ? "未关联" : profile.mapping.status === "ambiguous" ? "关联不唯一" : "关联未核验"} · {profile.mapping.method} · 版本 {profile.mapping.version || "未提供"}</dd><dt>类目证据</dt><dd>{profile.categoryEvidence.status === "verified_id" ? "版本化类目ID" : profile.categoryEvidence.status === "label_only" ? "仅来源标签" : "类目未知"} · {profile.categoryEvidence.version || "未提供版本"}</dd><dt>资料质量</dt><dd>{profile.quality.length ? profile.quality.map(reason => productReasonLabels[reason] ?? reason).join(" / ") : "本来源未报告资料问题"}</dd></dl><p className="np-note">价格、库存及目录映射分别属于当前快照，不代表所选历史期间的售价、库存或SKU归属。</p></>;
}
function DailySection({ data, onDay }: { data: ProductDailyData; onDay?: (date: string) => void }) {
  const keys = [...new Set(data.items.flatMap(row => Object.keys(row.metrics)))]; const hasVisitorValue = data.items.some(row => row.visitorValue !== undefined);
  return <><p className="np-caption">{sourceLabels[data.source]} · {data.startDate} — {data.endDate}</p><div className="np-table-wrap"><table className="np-table"><thead><tr><th>日期</th>{keys.map(key => <th key={key} className="np-number">{labels[key] ?? key}</th>)}{hasVisitorValue && <th>商品访客累计价值</th>}</tr></thead><tbody>{data.items.map(row => <tr key={`${row.source}:${row.date}`}><td>{onDay ? <button type="button" className="np-link" onClick={() => onDay(row.date)}>{row.date}</button> : row.date}</td>{keys.map(key => <td key={key} className="np-number">{key in row.metrics ? <MetricCell metric={row.metrics[key as keyof typeof row.metrics]} /> : "— · 来源不适用"}</td>)}{hasVisitorValue && <td>{row.visitorValue ? <DerivedMoneyCell metric={row.visitorValue} /> : "— · 来源未提供"}</td>}</tr>)}</tbody></table>{data.items.length === 0 && <p className="np-empty">本来源在当前对象和期间没有记录</p>}</div><details className="np-note"><summary>字段定义与来源版本</summary><ul>{data.definitions.map(text => <li key={text}>{text}</li>)}</ul><ul>{data.sourceRevisions.map(revision => <li key={`${revision.domain}:${revision.kind}:${revision.scopeKey}`}>{revision.domain} / {revision.kind}：{revision.revision}</li>)}</ul></details></>;
}

export function ProductDetail({ props, ui, onUi, onContextAvailable }: { props: NetshopColumnProps; ui: ProductsUiState; onUi: ProductsUiChange; onContextAvailable: (context: InsightsContext, categories: string[]) => void }) {
  const source: ProductSource = ui.detailSource;
  const section: ProductSection = productSections.includes(props.context.section as ProductSection) ? props.context.section as ProductSection : "overview";
  const read = useProductRead(productsQuery(props, ui.sort, { section, source, page: props.context.page }), productPrincipalKey(props), readDetail);
  const data = read.data;
  useEffect(() => { if (data) onContextAvailable(data.context, []); }, [data, onContextAvailable]);
  const daily = section === "trends" ? data?.sections.trends : data?.sections.daily;
  const profile = data?.sections.catalog;
  return <div className="np-stack"><div className="np-row"><button type="button" onClick={props.onReturn}>← 返回商品列表</button><button type="button" onClick={read.refresh}>刷新当前对象</button></div><nav className="np-chapter-nav" aria-label="单品详情分区">{productSections.map(key => <button type="button" key={key} className={section === key ? "np-active" : ""} aria-pressed={section === key} onClick={() => props.onContextChange({ section: key, page: 1 })}>{sectionLabels[key]}</button>)}</nav>
    {(section === "daily" || section === "trends") && <div className="np-toolbar"><label>明细来源 <select aria-label="单品明细来源" value={source} onChange={event => { onUi({ ...ui, detailSource: event.target.value as ProductSource }, { page: 1 }); }}>{Object.entries(sourceLabels).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select></label><p className="np-caption">平台成交、广告归因与ERP净销售分别展开。</p></div>}
    {!data ? <InsightReadState status={read.status} error={read.error} onRetry={read.refresh} /> : <>
      <ProductsPanel title={data.sections.performance.title} note={`${data.identity.platform} · ${data.identity.shopName} · ${data.identity.dimension.toUpperCase()} ${data.identity.id}`}><div className="np-row"><ProductPicture title={data.sections.performance.title} url={data.sections.performance.imageUrl} large /><p className="np-caption">精确身份：平台 + 店铺 + 维度 + ID；金额口径分组，不按名称合并。</p></div></ProductsPanel>
      {section === "overview" && <ProductsPanel title="两期经营成绩" note="平台商品日报；人数为商品×日累计"><div className="np-metrics">{Object.entries(data.sections.performance.metrics).map(([key, metric]) => <ProductsMetric key={key} label={labels[key] ?? key} metric={metric} previous={data.sections.performance.comparisons[key as keyof typeof data.sections.performance.comparisons].previous} yearAgo={data.sections.performance.comparisons[key as keyof typeof data.sections.performance.comparisons].yearAgo} showPrevious={props.context.previous} showYearAgo={props.context.yearAgo} />)}</div>{(["previous", "yearAgo"] as const).map(key => (key === "previous" ? props.context.previous : props.context.yearAgo) && data.sections.baselineReads[key].state === "error" ? <p className="np-notice" role="status" key={key}>{key === "previous" ? "环比" : "同比"}来源读取失败，保留本期可靠结果：{data.sections.baselineReads[key].message}</p> : null)}</ProductsPanel>}
      {section === "catalog" && <ProductsPanel title="单品资料与当前快照">{profile && profile.state === "ready" ? profile.data ? <CatalogProperties profile={profile.data} /> : <MissingSource title="该对象尚未关联目录档案" reason="no_records" /> : profile ? <SourceError title="目录资料" section={profile} /> : <MissingSource title="目录资料" reason="unverified_source" />}</ProductsPanel>}
      {(section === "daily" || section === "trends") && <ProductsPanel title={`${sourceLabels[source]}${section === "daily" ? "逐日明细" : "独立趋势"}`} note="只显示已读取日期；缺日留空，分页与来源版本绑定">{daily?.state === "ready" ? <>{section === "trends" && data.sections.visitorValue && <ProductsDerivedMetric label="商品访客累计价值" metric={data.sections.visitorValue} />}{section === "trends" && <div className="np-even">{[...new Set(daily.data.items.flatMap(row => Object.keys(row.metrics)))].map(key => <ProductsPanel key={key} title={labels[key] ?? key}><ProductsTrend label={labels[key] ?? key} points={daily.data.items.filter(row => key in row.metrics).map(row => ({ date: row.date, metric: row.metrics[key as keyof typeof row.metrics] }))} /></ProductsPanel>)}</div>}<DailySection data={daily.data} onDay={props.onApplyPeriod ? date => props.onApplyPeriod?.(date, date) : undefined} /><InsightListPagination pagination={daily.data.pagination} onPage={page => props.onContextChange({ page })} /></> : daily ? <SourceError title={sourceLabels[source]} section={daily} /> : <MissingSource title={`${sourceLabels[source]}${sectionLabels[section]}`} reason="unverified_source" />}</ProductsPanel>}
      {section === "sku" && <ProductsPanel title="历史SKU贡献" note="必须具备所选历史期间的SKU–SPU归属版本">{data.sections.skuContribution?.status === "available" ? <><p className="np-caption">历史归属版本 {data.sections.skuContribution.relationVersion}</p><ProductRows rows={data.sections.skuContribution.items} columns={ui.columns} previous={props.context.previous} yearAgo={props.context.yearAgo} onSelect={row => props.onDrill("products", row.identity, "overview")} /><InsightListPagination pagination={data.sections.skuContribution.pagination} onPage={page => props.onContextChange({ page })} /></> : <MissingSource title="历史SKU归属尚未具备" reason={data.sections.skuContribution?.reasonCode ?? "unverified_source"}><p>当前目录关系不会被回填成历史贡献。</p></MissingSource>}</ProductsPanel>}
      {section === "promotion" && <ProductsPanel title="推广关联" note="广告归因成交与平台销售额分别统计">{data.sections.promotion.state === "ready" ? <><div className="np-metrics">{Object.entries(data.sections.promotion.data.metrics).map(([key, metric]) => <ProductsMetric key={key} label={labels[key] ?? key} metric={metric} />)}</div><p className="np-note">映射：{productMappingLabels[data.sections.promotion.data.mapping.status]} · 版本 {data.sections.promotion.data.mapping.version || "未验证"}；归因窗口 {data.sections.promotion.data.attributionWindow || "未核验"}。ROAS是归因成交 ÷ 花费，不代表利润或广告增量。</p></> : <SourceError title="推广" section={data.sections.promotion} />}<div className="np-toolbar"><button type="button" onClick={() => props.onDrill("promotion", data.identity, "product")}>进入推广分析</button></div></ProductsPanel>}
      {section === "erp" && <ProductsPanel title="ERP经营关联" note="ERP净销售、成本、订单毛利、大毛利率及退货分别保留原定义">{data.sections.erp.state === "ready" ? <><div className="np-metrics">{Object.entries(data.sections.erp.data.metrics).map(([key, metric]) => <ProductsMetric key={key} label={labels[key] ?? key} metric={metric} />)}</div><p className="np-note">映射：{productMappingLabels[data.sections.erp.data.mapping.status]} · {data.sections.erp.data.mapping.method} · 版本 {data.sections.erp.data.mapping.version || "未核验"}。未关联指标为空，不默认零成本、零毛利。</p></> : <SourceError title="ERP" section={data.sections.erp} />}</ProductsPanel>}
      {section === "trends" && <p className="np-note">当前按真实来源展示本期日序列；基期逐日趋势尚未具备，不用汇总金额分配或补零生成趋势。</p>}<details className="np-note"><summary>本对象来源与口径限制</summary><ul>{data.sections.metadata.limitations.map(text => <li key={text}>{text}</li>)}</ul><p>类目口径：{data.sections.metadata.categoryBasis}；价格带口径：{data.sections.metadata.priceBasis}。</p></details>
      <ProductsCoverage context={data.context} revisions={data.joinedSourceRevisions} />
      {section === "overview" && <ProductsPanel title="实际基期成绩" note="已按当前精确商品身份配对；缺失、零与负基期分别保留"><div className="np-even">{(["previous", "yearAgo"] as const).filter(key => key === "previous" ? props.context.previous : props.context.yearAgo).map(key => <ProductsPanel key={key} title={key === "previous" ? "环比基期" : "同比基期"} note={`${data.context.periods[key].startDate} — ${data.context.periods[key].endDate}`}><div className="np-metrics">{Object.entries(data.sections.performance.baselineMetrics[key]).map(([metricKey, metric]) => <ProductsMetric key={metricKey} label={labels[metricKey] ?? metricKey} metric={metric} />)}</div></ProductsPanel>)}</div>{data.sections.visitorValue && <ProductsDerivedMetric label="商品访客累计价值" metric={data.sections.visitorValue} />}</ProductsPanel>}
    </>}
  </div>;
}
