import {shops,products,aggregate,promotion,money,percent,escape,ratio,createModel} from './data.js';
export const titles={results:'经营结果与目标',trend:'关键经营趋势',shops:'平台与店铺贡献',products:'商品与品类贡献',promotion:'推广投入与效率',inventory:'库存与供货风险',finance:'月度盈利摘要',quality:'数据质量与经营提示'};
const routes={sales:'?module=sales&view=overview',shop:'?module=shop&view=analysis',products:'?module=product&view=overview',promotion:'?module=shop&view=promotion',inventory:'?module=inventory&view=plan',finance:'?module=sales&view=finance',quality:'?module=import&view=chains'};
export const movement=(v,suffix='%')=>v===null?'<span class="muted">不可比较</span>':`<span class="${v>0?'up':v<0?'down':'neutral'}">${v>0?'+':''}${suffix==='%'?(v*100).toFixed(1):v.toFixed(1)}${suffix}</span>`;
const action=(act,val,label,cls='')=>`<button class="${cls}" data-action="${act}" data-value="${escape(val)}">${label}</button>`;
const field=(key,options,value,label)=>`<label>${label}<select data-field="${key}">${options.map(([v,l])=>`<option value="${v}" ${value===v?'selected':''}>${l}</option>`).join('')}</select></label>`;
const sum=(rows,key)=>rows.some(r=>r[key]!==null)?rows.reduce((a,r)=>a+(r[key]??0),0):null;
export function createUI(ctx){
 const {state:s,model:m}=ctx,t=m.totals;
 const panel=(title,body,subtitle='')=>`<section class="panel"><header class="section-head"><div><h2>${title}</h2>${subtitle?`<p class="caption">${subtitle}</p>`:''}</div></header>${body}</section>`;
 function kpis(){
  const complete=t.coverage.complete;
  const cells=[['ERP 净销售额',money(t.sales),`已知来源${complete?'全量':'小计'} · ${movement(t.change)} ${s.compare==='year'?'同比':'等长前期'}`],['综合大毛利额',money(t.profit),`净销售 − 成本 · ${movement(t.profitChange)}`],['综合大毛利率',percent(t.margin),`汇总毛利 / 净销售 · ${movement(t.marginPp,' pp')}`],['退货金额',money(t.returns),`退货 / 正向销售 ${percent(t.returnRate)} · ${movement(t.returnPp,' pp')}`],['ERP 同口径目标',percent(ratio(t.sales,t.target)),`合成日计划合计 ${money(t.target)} · ${t.sales===null?'无记录':`${t.sales>t.target?"超目标":"距目标"} ${money(Math.abs(t.target-t.sales))}`}`],['推广 ROAS',t.roas===null?'未覆盖':t.roas.toFixed(2)+' 倍',`归因成交 / 花费 · ${m.totals.promotionCoverage.covered}/${m.totals.promotionCoverage.expected}店日`]];
  return `<div class="kpis">${cells.map(([l,v,n],i)=>`<article class="kpi" data-kpi="${i}"><h3>${l}</h3><strong>${v}</strong><p class="caption">${n}</p></article>`).join('')}</div><p class="caption">毛利为综合大毛利，尚未扣除月度运营费用。退货率下降可改善经营；颜色只表达数值方向。${complete?'':'缺来源：以上是已覆盖小计，不能代表全公司完整表现。'}</p>`;
 }
 function trend(metric='sales'){
  const series=m.trends,key=metric;
  const values=series.flatMap(p=>[p[key],...(key==='sales'?[p.profit]:[])]).filter(v=>v!==null);
  if(!values.length)return '<div class="empty">所选期无可用趋势记录。未导入不当作零。</div>';
  const min=Math.min(0,...values),max=Math.max(0,...values),range=max-min||1;
  const W=800,H=205,L=65,R=20,T=18,B=35,scale=v=>T+(max-v)/range*(H-T-B),x=i=>L+(W-L-R)*i/Math.max(1,series.length-1);
  const path=k=>{let open=false;return series.map((p,i)=>{if(p[k]===null){open=false;return '';}let out=`${open?'L':'M'}${x(i).toFixed(1)},${scale(p[k]).toFixed(1)}`;open=true;return out;}).join(' ');};
  const label=key==='spend'?'推广花费（元）':key==='profit'?'综合大毛利（元）':'净销售 / 综合大毛利（元，共用尺度）';
  return `<div class="chart"><p class="caption">${label} · 点击点查看该期证据；负值在零线下方</p><div class="chart-plot"><svg viewBox="0 0 ${W} ${H}" role="img" aria-label="${label}趋势"><line x1="${L}" x2="${W-R}" y1="${scale(0)}" y2="${scale(0)}" class="zero"/>${[max,(max+min)/2,min].map(v=>`<line x1="${L}" x2="${W-R}" y1="${scale(v)}" y2="${scale(v)}" class="grid-line"/>`).join('')}<path d="${path(key)}" class="line-main"/>${key==='sales'?`<path d="${path('profit')}" class="line-profit"/>`:''}${series.map((p,i)=>p[key]===null?'':`<g><circle cx="${x(i)}" cy="${scale(p[key])}" r="${series.length>35?3:5}" data-action="select-date" data-value="${p.date}" tabindex="0" role="button" aria-label="查看 ${p.date} 证据"><title>${p.date}—${p.end}：${money(p[key])}；毛利 ${money(p.profit)}；ROAS ${p.roas===null?'未覆盖':p.roas.toFixed(2)}</title></circle></g>`).join('')}</svg>${[max,(max+min)/2,min].map(v=>`<span class="chart-axis" style="top:${scale(v)/H*100}%">${(v/10000).toFixed(1)}万</span>`).join("")}</div><div class="chart-dates caption"><span>${s.start}</span><span>${s.end}</span></div><div class="row caption"><span class="legend">● ${key==='spend'?'花费':'ERP 净销售'}</span>${key==='sales'?'<span class="legend profit">● 综合大毛利</span>':''}${field('evidenceDate',[['','选择期间查看数值'],...series.map(p=>[p.date,`${p.date}—${p.end}`])],s.evidenceDate,'数值查看')}</div>${s.evidenceDate?evidence(true):''}</div>`;
 }
 function shopTable(){
  const list=[...m.shops].filter(r=>r.name.includes(s.qShop||''));
  list.sort((a,b)=>{let key=s.rank==='profit'?'profit':s.rank==='delta'?'delta':'sales';return (b[key]??-Infinity)-(a[key]??-Infinity);});
  const shown=s.allShops?list:list.slice(0,5);
  const platforms=[...new Set(m.shops.map(r=>r.platform))].map(p=>{const rows=m.shops.filter(r=>r.platform===p),sales=sum(rows,'sales'),profit=sum(rows,'profit');return `<span class="tag">${p}：${money(sales)} · 毛利 ${money(profit)} · 占已知 ${percent(ratio(sales,t.sales))}</span>`;}).join('');
  return `<div class="chips">${platforms}</div><div class="table-tools">${field('rank',[['sales','净销售额'],['profit','综合大毛利额'],['delta','销售增减额']],s.rank,'排名指标')}<label>店名筛选<input data-field="qShop" value="${escape(s.qShop)}" placeholder="搜索全部店铺"/></label>${action('all-shops','','查看'+(s.allShops?'前五':'全部')+'店铺')}</div><div class="table-scroll"><table><thead><tr><th>平台 / 店铺</th><th>净销售额</th><th>毛利额 / 率</th><th>销售贡献</th><th>增减额 / 幅</th><th>增长贡献</th><th>证据</th></tr></thead><tbody>${shown.map(r=>`<tr class="${s.selectedShop===r.id?'selected':''}"><td>${action('select-shop',r.id,escape(r.name),'text-button')}<small>${r.platform}${r.coverage.complete?'':' · 来源不足'}</small></td><td>${money(r.sales)}</td><td>${money(r.profit)}<small>${percent(r.margin)}</small></td><td>${percent(r.share)}</td><td>${r.coverage.complete?money(r.delta):'基期/来源不足'}<small>${movement(r.change)}</small></td><td>${percent(r.growthContribution)}</td><td>${action('detail-shop',r.id,'单店详情')}</td></tr>`).join('')||'<tr><td colspan="7">没有匹配店铺；筛选保留。</td></tr>'}</tbody></table></div><p class="caption">显示 ${shown.length}/${list.length} 店 · 贡献分母是已覆盖净销售；增长贡献=本店增减 / 同期公司增减，仅完整两期可用，允许负贡献或超过100%。无基期不会标“新增”。</p>`;
 }
 function productTable(){
  const rows=m.products.filter(p=>p.name.includes(s.qProduct||'')).filter(p=>s.productFilter==='growth'?p.delta>0:s.productFilter==='decline'?p.delta<0:s.productFilter==='low'?p.margin!==null&&p.margin<.12:s.productFilter==='loss'?p.profit<0:true);
  const categories=[...new Set(m.products.map(r=>r.category))].map(c=>{const rows=m.products.filter(p=>p.category===c),sales=sum(rows,'sales'),profit=sum(rows,'profit');return `<div class="fact"><span>${c}</span><b>${money(sales)}</b><small>毛利 ${money(profit)} · 销售占比 ${percent(ratio(sales,t.sales))}</small></div>`;}).join('');
  return `<div class="grid3">${categories}</div><div class="table-tools">${field('productFilter',[['all','全部商品'],['growth','销售增长'],['decline','销售下降'],['low','低毛利 <12%'],['loss','负毛利']],s.productFilter,'重点商品')}<label>商品筛选<input data-field="qProduct" value="${escape(s.qProduct)}" placeholder="名称搜索"/></label></div><div class="table-scroll"><table><thead><tr><th>ERP SKU / 类目</th><th>净销售 / 占比</th><th>毛利 / 率</th><th>变化</th><th>库存关联</th></tr></thead><tbody>${rows.map(p=>`<tr><td>${action('detail-product',p.id,escape(p.name),'text-button')}<small>${p.id} · ${p.category}</small></td><td>${money(p.sales)}<small>${percent(p.share)}</small></td><td>${money(p.profit)}<small>${percent(p.margin)}</small></td><td>${p.coverage.complete?money(p.delta):'覆盖不足'}<small>${movement(p.change)}</small></td><td>${p.id==='K05'?'销量关联不完整':p.id==='K01'?'存在临界仓位':p.id==='K03'?'存在积压仓位':'已按合成ERP编码匹配'}</td></tr>`).join('')||'<tr><td colspan="5">没有匹配商品。</td></tr>'}</tbody></table></div><p class="caption">本表仅ERP SKU，不与平台 SPU 混加。结构变化需满足两期完整覆盖，再按增减筛选核对；不比较时仅展示本期结构。库存关系仅合成ERP编码，正式需验证历史身份。</p>`;
 }
 function ads(){
  if(s.status==='missing')return '<div class="empty warning">推广来源缺失（情景模拟），成交与花费均不可用。</div>';
  return `<div class="grid3"><div class="fact"><span>推广花费</span><b>${money(t.spend)}</b></div><div class="fact"><span>广告归因成交</span><b>${money(t.attributed)}</b></div><div class="fact"><span>ROAS</span><b>${t.roas===null?'未覆盖':t.roas.toFixed(2)+' 倍'}</b></div></div>${trend('spend')}<h3>花费与效率期间趋势</h3><div class="table-scroll"><table><thead><tr><th>期间</th><th>花费</th><th>归因成交</th><th>ROAS（倍）</th></tr></thead><tbody>${m.trends.map(p=>`<tr><td>${p.date}—${p.end}</td><td>${money(p.spend)}</td><td>${money(p.attributed)}</td><td>${p.roas===null?"未覆盖":p.roas.toFixed(2)}</td></tr>`).join("")}</tbody></table></div><div class="table-scroll"><table><thead><tr><th>店铺</th><th>花费</th><th>归因成交</th><th>ROAS</th></tr></thead><tbody>${m.shops.map(r=>`<tr><td>${action('detail-shop',r.id,escape(r.name),'text-button')}</td><td>${money(r.spend)}</td><td>${money(r.attributed)}</td><td>${r.roas===null?'未覆盖':r.roas.toFixed(2)+' 倍'}</td></tr>`).join('')}</tbody></table></div><p class="caption">ROAS＝广告归因成交÷花费，不是利润率，不与ERP净销售相加。归因口径：合成7日点击归因，跨平台仅作示例；正式保留各来源归因定义。</p><p class="notice">效率提示：可比广告店日若花费增而ROAS降，需检查流量价格与转化；只陈述同步变化，不推广告增量因果。当前花费变化 ${movement(t.spendChange)}，ROAS变化 ${movement(t.roasPp,' 倍')}；来源覆盖 ${t.promotionCoverage.covered}/${t.promotionCoverage.expected} 店日，缺数时此变化仅为来源小计参考。</p>`;
 }
 function stock(){const i=m.inventory;return `<p class="notice warning">库存快照 ${i.snapshot} · 库龄快照 ${i.ageSnapshot} · 相对演示今天2026-10-05已过期4天。销量需求窗口 ${i.demandStart}—${i.demandEnd}。公司库存，不按店铺或BI日选期拆分。</p><div class="grid3"><div class="fact"><span>当前库存货值（已覆盖成本）</span><b>${money(i.value)}</b><small>${i.uniqueProducts} 唯一SKU / ${i.warehousePositions} 商品仓位</small></div><div class="fact"><span>积压 / 180天以上货值</span><b>${money(i.agedValue)}</b><small>已匹配库存，不含销量未匹配</small></div><div class="fact"><span>有效补货建议</span><b>暂停采纳</b><small>理论缺口72件 / 2仓位；过期快照门禁</small></div></div><div class="table-scroll"><table><thead><tr><th>风险商品 / 仓</th><th>数量 / 覆盖天数</th><th>货值 / 库龄</th><th>需求与风险</th></tr></thead><tbody>${i.items.filter(r=>r.risk!=='正常').map((r,idx)=>`<tr><td>${action('detail-risk',r.id+'|'+r.warehouse,escape(r.name),'text-button')}<small>${r.id} · ${r.warehouse}</small></td><td>${r.qty} 件<small>${r.days===null?'未匹配':r.days+' 天'}</small></td><td>${money(r.value)}<small>${r.age} 天库龄</small></td><td>${r.risk}<small>${r.needed===null?'需求未知':`理论需求${r.needed}件；当前不可执行`}</small></td></tr>`).join('')}</tbody></table></div><p class="caption">1 个SKU的一个仓位销量未匹配，不归类低动销；同一SKU跨仓分别计仓位，唯一SKU去重计数。缺货/临界与积压风险按事实展示，不合成库存健康分。</p>`;}
 function financial(){const f=m.finance;return `<p class="caption">${f.scope} · 最近完整月 ${f.month} · ${f.status} · 缺失月份 ${f.missing.join('、')}</p><div class="grid3"><div class="fact"><span>财报利润</span><b>${money(f.profit)}</b><small>较2026-07完整前月 ${money(f.profit-f.previousProfit)} / ${movement((f.profit-f.previousProfit)/f.previousProfit)}</small></div><div class="fact"><span>同口径利润目标</span><b>${percent(f.profit/f.target)}</b><small>目标 ${money(f.target)} · 差距 ${money(f.target-f.profit)}</small></div><div class="fact"><span>财报净销售</span><b>${money(f.revenue)}</b><small>财报月口径，不等同选期ERP销售</small></div></div><div class="table-scroll"><table><thead><tr><th>费用</th><th>本月</th><th>前月增减</th></tr></thead><tbody>${f.expenses.map(e=>`<tr><td>${e.name}</td><td>${money(e.value)}</td><td>${money(e.value-e.previous)}</td></tr>`).join('')}</tbody></table></div><p class="notice">不拆成日利润。9月缺失，不用8月利润替代9月。费用变化与利润为独立财报事实，未提供利润完整桥接时不硬凑等式。</p>`;}
 function quality(){return `<div class="table-scroll"><table><thead><tr><th>来源</th><th>截止 / 范围</th><th>质量与可比较资格</th></tr></thead><tbody><tr><td>ERP 销售</td><td>2026-10-04 · 2025-01-01起合成事实</td><td>${t.coverage.covered}/${t.coverage.expected}店日；新店基期/待接入店缺失；${t.comparable?'支持当前比较':'当前全范围不支持严格比较'}</td></tr><tr><td>推广</td><td>2026-10-02 · 京东/天猫示例</td><td>${t.promotionCoverage.covered}/${t.promotionCoverage.expected}店日；企业采购不适用，不补零</td></tr><tr><td>库存 / 库龄</td><td>2026-10-01 公司8仓位</td><td>过期4天；1仓位销量未匹配；暂停有效补货建议</td></tr><tr><td>财报 / 目标</td><td>2026-08完整 · 9月缺失</td><td>财报目标同月口径；ERP日计划为需补源的合成演示</td></tr><tr><td>市场 / 客服 / 运营</td><td>2026-09-30 已采集榜单 / 会话标注</td><td>覆盖有限，不代表行业份额/订单归因</td></tr></tbody></table></div><div class="grid3"><div class="notice">市场：已采集切肉机榜单低价段竞争增加。${action('module','?module=market&view=ranking','查看榜单证据')}</div><div class="notice">客服：会话标注中交期咨询增加，无可靠订单关联。${action('module','?module=customer_service&view=conversations','查看会话摘要')}</div><div class="notice">运营：重点补齐9月财报与过期库存快照。${action('module','?module=workflow&view=plan','查看运营计划')}</div></div><p class="caption">完整日志、文件与任务不放首屏。${action('module','?module=import&view=history','查看批次来源')}${action('module','?module=n8n_workflows&view=jackyun','查看自动化链路')}</p>`;}
 function evidence(compact=false){
  const row=m.trends.find(p=>p.date===s.evidenceDate),ids=s.status==='empty'?[]:s.selectedShop?[s.selectedShop]:m.selectedShops.map(p=>p.id),selected=shops.filter(r=>ids.includes(r.id));
  const start=row?.date||s.start,end=row?.end||s.end;
  const a=aggregate(start,end,selected);
  const ps=products.map(p=>({...p,...aggregate(start,end,selected,[p])}));
  return `<div class="evidence"><div class="row"><h3>选中对象证据</h3>${action('reset-evidence','','清除局部选择')}</div><p class="caption">局部证据 ${start}—${end} · ${s.selectedShop?escape(shops.find(x=>x.id===s.selectedShop)?.name):'当前筛选店铺'}；上方经营汇总仍为全选期。</p><div class="grid2"><div class="fact"><span>局部ERP净销售</span><b>${money(a.sales)}</b></div><div class="fact"><span>局部综合大毛利</span><b>${money(a.profit)}</b></div></div>${compact?'':`<div class="table-scroll"><table><thead><tr><th>SKU证据</th><th>净销售</th><th>综合大毛利</th></tr></thead><tbody>${ps.map(p=>`<tr><td>${action('detail-product',p.id,escape(p.name),'text-button')}</td><td>${money(p.sales)}</td><td>${money(p.profit)}</td></tr>`).join('')}</tbody></table></div>`}${s.selectedShop?action('detail-shop',s.selectedShop,'打开单店详情'):''}</div>`;
 }
 function contribution(level){
  let ss=m.selectedShops.filter(x=>(!s.explorePlatform||x.platform===s.explorePlatform)&&(!s.exploreShop||x.id===s.exploreShop)),pp=products.filter(x=>!s.exploreCategory||x.category===s.exploreCategory),groups=[];
  if(level==='platform')groups=[...new Set(ss.map(x=>x.platform))].map(v=>({name:v,act:'explore-platform',val:v,ss:ss.filter(x=>x.platform===v),pp}));
  if(level==='shop')groups=ss.map(x=>({name:x.name,act:'explore-shop',val:x.id,ss:[x],pp}));
  if(level==='category')groups=[...new Set(pp.map(x=>x.category))].map(v=>({name:v,act:'explore-category',val:v,ss,pp:pp.filter(x=>x.category===v)}));
  if(level==='product')groups=pp.map(x=>({name:x.name,act:'explore-product',val:x.id,ss,pp:[x]}));
  const list=groups.map(g=>({...g,a:aggregate(s.start,s.end,g.ss,g.pp)})),key=s.exploreMetric==='profit'?'profit':'sales',max=Math.max(1,...list.map(g=>Math.abs(g.a[key]||0))),parent=aggregate(s.start,s.end,ss,pp);
  return `<p class="caption">ERP${key==='sales'?'净销售':'综合大毛利'}贡献 · 金额相加；占比基于当前父范围${money(parent[key])}。不是因果分解。</p><div class="contribution-list">${list.map(g=>`<div class="contribution-row"><div>${action(g.act,g.val,escape(g.name),'text-button')}<small>${g.a.coverage.complete?'完整店日':'来源不足：仅已知小计'}</small></div><div class="signed-bar"><i class="${g.a[key]<0?'negative':''}" style="width:${Math.abs(g.a[key]||0)/max*45}%;${g.a[key]<0?'right:50%':'left:50%'}"></i></div><div>${money(g.a[key])}<small>${percent(ratio(g.a[key],parent[key]))}</small></div></div>`).join('')||'<div class="empty">当前路径无可拆解记录。</div>'}</div><p class="caption">左负右正，以父级内最大绝对金额统一尺度；零线在中间。无法可靠关联的平台商品SPU在此停止。</p>`;
 }
 const sections={results:kpis,trend,shops:shopTable,products:productTable,promotion:ads,inventory:stock,finance:financial,quality};
 return {panel,kpis,trend,shopTable,productTable,inventory:stock,finance:financial,quality,promotion:ads,evidence,contribution,section:key=>`<section class="panel" id="${key}" data-domain="${key}"><header class="section-head"><div><h2>${titles[key]}</h2></div>${routes[key]?action('module',routes[key],'进入专业模块 · 演示'):''}</header>${sections[key]()}</section>`};
}
