import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {createHash} from 'node:crypto';
import path from 'node:path';
import {retryReadOnlyObservation,parseStatus,assertCompleteReadiness,observationError,safeObservationError,safeReadinessFailure,readinessComponents} from '../tools/release-readonly-retry.mjs';
const text=await readFile(new URL('../tools/release-batch.mjs',import.meta.url),'utf8');
const body=text.slice(text.indexOf('export async function runApprovedOperation('),text.indexOf('\nexport async function cancelUnswitchedBatch')).replace(/^export /,'');
const canonical=v=>Array.isArray(v)?'['+v.map(canonical).join(',')+']':v&&typeof v==='object'?'{'+Object.keys(v).sort().map(k=>JSON.stringify(k)+':'+canonical(v[k])).join(',')+'}':JSON.stringify(v);
const hash=v=>createHash('sha256').update(typeof v==='string'?v:canonical(v)).digest('hex');
const releaseId='20261010T014638Z-97833d2f2b7e7bc9';
const good=()=>({state:'Running',backendState:'Ready',workerState:'exact_release',releaseId,components:Object.fromEntries(readinessComponents.map(n=>[n,true]))});
function fixture(stdout,extraAssertions=[]){
  const exe='C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe',script='D:\\运营管理系统\\tools\\operations-system-control.ps1';
  const op={id:'synthetic-readonly-status',kind:'command',phase:'closeout',mutating:false,readOnlyRetry:{totalTimeoutMs:4000},command:{executable:exe,cwd:'isolated-synthetic-only',args:['-NoProfile','-NonInteractive','-File',script,'-Action','Status','-Json'],files:[exe,script].map(p=>({path:p,sha256:'a'.repeat(64)}))},assertions:[{path:'releaseId',equals:releaseId},...extraAssertions]};
  const processEvidence={version:1,code:'completed',stage:'completed',processId:12345,exitCode:0,signal:null,timeoutType:null,deadlineUnixMs:Date.now()+60000,elapsedMs:1,outputProtocol:'direct-exit-files',cleanup:'direct',stdoutBytes:Buffer.byteLength(stdout),stderrBytes:0,stdoutSha256:hash(stdout),stderrSha256:hash(''),treeCleanupPending:false,treeCleanupExitCode:null,nativeCode:null};
  let queries=0;const records=[];
  const run=new Function('validateOperation','processDeadline','safeFileDigest','productionCommandArguments','productionCommandEnvironment','assertStartBinding','runProcess','runReadOnlyProcess','retryReadOnlyObservation','parseStatus','assertCompleteReadiness','observationError','canonical','hash','requireHash','path','append','safeReadinessFailure',body+';return runApprovedOperation;')(
    o=>assert.equal(o.mutating,false),()=>processEvidence.deadlineUnixMs,async()=> 'a'.repeat(64),(_,args)=>args,()=>({}),()=>{},async()=>{throw new Error('ordinary runner must not be used');},async()=>{queries++;return{stdout,processEvidence};},retryReadOnlyObservation,parseStatus,assertCompleteReadiness,observationError,canonical,hash,s=>assert.match(s,/^[a-f0-9]{64}$/),path,async(_state,_batch,record)=>records.push(record),safeReadinessFailure);
  return{run:()=>run(op,{batch:{id:'synthetic-only',recovery:{mode:'full'}},lease:{},state:{latest:new Map()}}),processEvidence,records,get queries(){return queries;}};
}
test('NotReady retains actual successful probe process and only the failed component facts, no retry',async()=>{const status=good();status.backendState='NotReady';status.components.finance=false;status.reason='PRIVATE_CUSTOMER_BODY';const f=fixture(JSON.stringify(status));let error;try{await f.run();}catch(e){error=e;}assert.equal(error.code,'STATUS_NOT_READY');assert.equal(f.queries,1);assert.deepEqual(error.processEvidence,f.processEvidence);const record=f.records[0].observation;assert.equal(record.error.retryable,false);assert.equal(record.error.process.processId,12345);assert.equal(record.error.readiness.components.finance,false);assert.equal(record.error.readiness.releaseMatchesExpected,true);assert.ok(!JSON.stringify(record).includes('PRIVATE_CUSTOMER_BODY'));});
test('wrong release remains nonretryable identity failure with actual process evidence',async()=>{const v=good();v.releaseId='PRIVATE_WRONG_ID';const f=fixture(JSON.stringify(v));await assert.rejects(f.run,e=>e.code==='STATUS_IDENTITY_MISMATCH'&&e.processEvidence===f.processEvidence);assert.equal(f.queries,1);assert.equal(f.records[0].observation.error.readiness.releaseMatchesExpected,false);assert.ok(!JSON.stringify(f.records).includes('PRIVATE_WRONG_ID'));});
test('invalid JSON retains real output hash/process without retaining or inventing a parsed snapshot',async()=>{const f=fixture('PRIVATE_INVALID_JSON');await assert.rejects(f.run,e=>e.code==='INVALID_STATUS_JSON'&&e.processEvidence===f.processEvidence);const e=f.records[0].observation.error;assert.equal(e.process.stdoutSha256,hash('PRIVATE_INVALID_JSON'));assert.equal(e.readiness,undefined);assert.equal(f.queries,1);assert.ok(!JSON.stringify(e).includes('PRIVATE_INVALID_JSON'));});
test('an additional original assertion still rejects and retains the same actual probe',async()=>{const v=good();v.extraValue='PRIVATE_WRONG_VALUE';const f=fixture(JSON.stringify(v),[{path:'extraValue',equals:'expected'}]);await assert.rejects(f.run,e=>e.code==='ASSERTION_FAILED'&&e.processEvidence===f.processEvidence);assert.equal(f.queries,1);assert.ok(!JSON.stringify(f.records).includes('PRIVATE_WRONG_VALUE'));});
test('healthy original observation stays passed with original receipt and no failure snapshot',async()=>{const v=good(),f=fixture(JSON.stringify(v)),r=await f.run();assert.equal(r.status,'passed');assert.equal(r.receiptSha256,hash(v));assert.equal(r.processEvidence.processId,12345);assert.equal(f.queries,1);assert.equal(f.records[0].observation.status,'passed');assert.equal(f.records[0].observation.error,null);});
test('snapshot strips arbitrary fields, unknown strings and extra component names',()=>{const v=good();v.state='PRIVATE_STATE';v.reason='PRIVATE_REASON';v.components.PRIVATE_COMPONENT='PRIVATE_VALUE';v.components.core='PRIVATE_BOOLEAN';const e=safeObservationError(Object.assign(observationError('STATUS_NOT_READY'),{readinessEvidence:safeReadinessFailure(v,releaseId),stdout:'PRIVATE_STDOUT',argv:['PRIVATE_ARGV']}));assert.equal(e.readiness.state,'unrecognized');assert.equal(e.readiness.components.core,null);assert.equal(e.readiness.unexpectedComponentCount,1);assert.ok(!JSON.stringify(e).includes('PRIVATE_'));});
test('snapshot counts missing, array and inherited components without treating them as observed booleans',()=>{const inherited=Object.create({core:true});inherited.finance=false;const s=safeReadinessFailure({components:inherited},releaseId);assert.ok(s.missingComponents.includes('core'));assert.equal(s.components.core,null);assert.equal(s.components.finance,false);const arr=safeReadinessFailure({components:[true]},releaseId);assert.equal(arr.componentObject,false);assert.equal(arr.componentCount,0);assert.equal(arr.missingComponents.length,12);});
test('all original readiness assertions still reject a missing or extra component',()=>{const missing=good();delete missing.components.ai;assert.throws(()=>assertCompleteReadiness(missing,releaseId),e=>e.code==='STATUS_NOT_READY');const extra=good();extra.components.other=true;assert.throws(()=>assertCompleteReadiness(extra,releaseId),e=>e.code==='STATUS_NOT_READY');});
test('the actual admission query also retains its failed original Status probe',async()=>{const source=await readFile(new URL('../tools/release-batch-admission.mjs',import.meta.url),'utf8'),start=source.indexOf('query:async({remaining})=>{'),end=source.indexOf('\n      }}));',start);assert.ok(start>=0&&end>start);const queryText=source.slice(start,end)+'\n      }';const v=good();v.components.ai=false;const processEvidence=fixture(JSON.stringify(v)).processEvidence;const query=new Function('runReadOnlyPowerShell','parseStatus','assertCompleteReadiness','plan','safeReadinessFailure','return ({'+queryText+'}).query;')(async()=>({stdout:JSON.stringify(v),processEvidence}),parseStatus,assertCompleteReadiness,{candidate:{releaseId}},safeReadinessFailure);let error;try{await query({remaining:()=>60000});}catch(e){error=e;}assert.equal(error.code,'STATUS_NOT_READY');assert.equal(error.processEvidence,processEvidence);const safe=safeObservationError(error);assert.equal(safe.readiness.components.ai,false);assert.equal(safe.retryable,false);assert.equal(safe.process.stdoutSha256,processEvidence.stdoutSha256);});
test('classified transient retry remains bounded and unknown errors remain nonretryable',async()=>{let now=0,calls=0;const records=[];const value=await retryReadOnlyObservation({stage:'synthetic-status',totalTimeoutMs:10000,now:()=>now,sleep:async ms=>{now+=ms;},onAttempt:async r=>records.push(r),query:async()=>{calls++;if(calls===1)throw observationError('STATUS_TIMEOUT');return 'ready';}});assert.equal(value.value,'ready');assert.equal(calls,2);assert.equal(records[0].error.retryable,true);assert.equal(records[1].status,'passed');calls=0;await assert.rejects(()=>retryReadOnlyObservation({stage:'synthetic-status',query:async()=>{calls++;throw new Error('PRIVATE_UNKNOWN');}}));assert.equal(calls,1);});

test('thrown failures never expose the raw status and safe serialization is idempotent',async()=>{const v=good();v.backendState='NotReady';v.reason='PRIVATE_REASON';v.components.PRIVATE_EXTRA='PRIVATE_VALUE';const f=fixture(JSON.stringify(v));let error;try{await f.run();}catch(e){error=e;}assert.ok(!JSON.stringify(error).includes('PRIVATE_'));const once=safeObservationError(error),twice=safeObservationError(once);assert.deepEqual(twice,once);assert.equal(once.readiness.releaseMatchesExpected,true);assert.equal(once.readiness.unexpectedComponentCount,1);assert.equal(twice.process.processId,12345);});
