// Meaningful design QA only; this does not validate production services or PostgreSQL.
import { createRequire } from 'node:module';
import { mkdir, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import path from 'node:path';
const require = createRequire(import.meta.url);
if (!process.env.TERUISI_DEMO_TOOLING) throw new Error('Set TERUISI_DEMO_TOOLING to the bundled Node package directory.');
const { chromium } = require(require.resolve('playwright', { paths: [process.env.TERUISI_DEMO_TOOLING] }));
const dir = path.dirname(fileURLToPath(import.meta.url));
const evidence = path.join(dir, 'evidence');
await mkdir(evidence, { recursive: true });
const browser = await chromium.launch({ channel: 'msedge', headless: true });
const errors = [];
const requests = [];
const checks = [];
const page = await browser.newPage({ viewport: { width: 1600, height: 1100 } });
page.on('pageerror', error => errors.push(error.message));
page.on('request', request => requests.push(request.url()));
const check = (name, ok, detail = null) => { checks.push({ name, ok, detail }); if (!ok) throw new Error(name + ': ' + JSON.stringify(detail)); };
const goto = layout => page.goto(`http://127.0.0.1:3196/?layout=${layout}`);
const overview = () => page.locator('.kpi-value').allTextContents();
try {
  for (let layout = 1; layout <= 5; layout++) {
    await goto(layout);
    check(`Layout ${layout}: title`, await page.locator('h1').innerText() === '推广分析');
    check(`Layout ${layout}: demo mark`, await page.locator('.demo-label').innerText() === '合成数据 / 未接业务');
    for (let section = 0; section < 8; section++) check(`Layout ${layout}: section ${section + 1}`, await page.locator(`#section-${section}`).count() === 1);
    await page.screenshot({ path: path.join(evidence, `desktop-0${layout}.png`), fullPage: false });
    await page.setViewportSize({ width: 390, height: 844 });
    const width = await page.evaluate(() => ({ viewport: innerWidth, content: document.documentElement.scrollWidth }));
    check(`Layout ${layout}: narrow width`, width.content <= width.viewport, width);
    await page.screenshot({ path: path.join(evidence, `mobile-0${layout}.png`), fullPage: false });
    await page.setViewportSize({ width: 1600, height: 1100 });
  }
  await goto(1);
  await page.locator('[data-action="platform"][data-value="tmall"]').click();
  check('Tmall attribution label', (await overview())[1].length > 0 && (await page.locator('.kpi-title').nth(1).innerText()).includes('推广净成交'));
  check('Tmall order unit', (await page.locator('.micro-metrics').innerText()).includes('净成交笔数'));
  await page.locator('#shop-select').selectOption('tm-a');
  check('Single shop hides duplicate comparison', (await page.locator('#section-2').innerText()).includes('收起重复'));
  await page.locator('[data-action="platform"][data-value="jd"]').click();
  const original = await overview();
  await page.locator('#object-search').fill('不存在的商品');
  check('List search keeps summary stable', JSON.stringify(await overview()) === JSON.stringify(original));
  check('Search empty state', (await page.locator('#section-3').innerText()).includes('没有匹配对象'));
  await page.locator('#object-search').fill('');
  await page.locator('#scenario-select').selectOption('partial');
  check('Incomplete fee stays null', (await overview())[3] === '—');
  await page.locator('#section-7 > summary').click();
  check('Partial fee discloses matched scope', (await page.locator('.basis-body').innerText()).includes('仅适用于 19/21 店日'));
  await page.locator('#scenario-select').selectOption('misaligned');
  check('Mismatched shop-day fee stays null', (await overview())[3] === '—');
  check('Mismatched shop-day pair count', (await page.locator('.context-line').innerText()).includes('配对 0/21'));
  await page.locator('#scenario-select').selectOption('missing');
  check('Missing clicks not zero', (await page.locator('.micro-metrics').innerText()).includes('点击 —'));
  check('Missing CTR/CPC unavailable', (await page.locator('.micro-metrics').innerText()).includes('CTR —') && (await page.locator('.micro-metrics').innerText()).includes('CPC —'));
  await page.locator('#scenario-select').selectOption('zero');
  check('Real zero preserved', (await overview())[0] === '0.00万元' && (await overview())[1] === '0.00万元');
  check('Zero denominator unavailable', (await overview())[2] === '—' && (await overview())[3] === '—');
  await page.locator('#scenario-select').selectOption('complete');
  await page.locator('.chart [data-date="2026-09-25"]').first().click();
  check('Trend date links object scope', (await page.locator('#section-3 h3').innerText()).includes('2026-09-25'));
  check('Date detail keeps period summary', JSON.stringify(await overview()) === JSON.stringify(original));
  await page.locator('[data-action="clear-date"]').first().click();
  await page.locator('[data-action="calendar"]').click();
  await page.locator('[data-action="date-preset"][data-value="yesterday"]').click();
  await page.locator('[data-action="close"]').last().click();
  check('Date cancel keeps scope', (await page.locator('.date-control').innerText()).includes('2026.09.23'));
  await page.locator('[data-action="calendar"]').click();
  await page.locator('[data-action="date-preset"][data-value="lastmonth"]').click();
  await page.locator('[data-action="calendar-apply"]').click();
  check('Date apply updates scope', (await page.locator('.date-control').innerText()).includes('2026.08.01'));
  await page.locator('[data-action="calendar"]').click();
  await page.locator('[data-action="date-preset"][data-value="last7"]').click();
  await page.locator('[data-action="calendar-apply"]').click();
  await page.locator('#grain-select').selectOption('week');
  check('Natural-week grouping labels', (await page.locator('.chart-note').first().innerText()).includes('自然周（首尾截段）'));
  await page.locator('#year-switch').check();
  check('Year comparison gap disclosed', (await page.locator('.prototype-note').first().innerText()).includes('同比来源未提供'));
  await goto(4);
  await page.locator('[data-action="object-tab"][data-value="plan"]').click();
  check('Unsupported plan shows gap', (await page.locator('.empty-state').first().innerText()).includes('来源受限'));
  await page.locator('[data-action="enable-detail"]').first().click();
  check('Supported scope bounded', await page.locator('#shop-select').inputValue() === 'jd-a');
  check('Same plan names retain separate IDs', (await page.locator('#section-3').innerText()).includes('P-1001') && (await page.locator('#section-3').innerText()).includes('P-1002'));
  await page.locator('[data-action="object-detail"]').nth(1).click();
  check('Plan detail matches exact ID', (await page.locator('.object-detail').innerText()).includes('P-1002'));
  check('Plan ID is not treated as product ID', await page.locator('.object-detail [data-action="product-link"]').count() === 0);
  await page.locator('[data-action="object-tab"][data-value="keyword"]').click();
  check('No-keyword ad kept separate', (await page.locator('#section-3').innerText()).includes('无词投放'));
  check('Search term gap is explicit', (await page.locator('#section-3').innerText()).includes('搜索词缺源'));
  await page.locator('[data-action="report-preview"]').first().click();
  check('Report preview does not claim real export', (await page.locator('.modal').innerText()).includes('不代表已接通真实导出'));
  await page.locator('[data-action="report-tab"][data-value="xlsx"]').click();
  check('XLSX scope/source structure', (await page.locator('.modal').innerText()).includes('完整筛选范围，非当前页'));
  await page.keyboard.press('Escape');
  check('Overlay escape closes', await page.locator('.overlay').count() === 0);
  await goto(3);
  await page.locator('[data-action="matrix-shop"][data-value="jd-b"]').click();
  check('Matrix selected-shop trend labeled', (await page.locator('#section-1 h3').innerText()).includes('厨电专营店'));
  await page.locator('#section-1 .chart [data-date="2026-09-25"]').hover();
  const hover = await page.locator('#section-1 .chart-tip').innerText();
  check('Matrix chart tooltip uses same shop scope', hover.includes('厨电专营店') && hover.includes('配对 1/1') && !hover.includes('商用设备店'), hover);
  await page.locator('#section-1 .chart [data-date="2026-09-25"]').click();
  check('Matrix date drill shows selected shop only', (await page.locator('#section-3 tbody').innerText()).includes('厨电专营店') && !(await page.locator('#section-3 tbody').innerText()).includes('商厨旗舰店'));
  await page.locator('[data-action="platform"][data-value="tmall"]').click();
  check('Platform change clears old date/shop drill', await page.locator('#section-3 tbody [data-action="object-detail"]').count() > 0 && !(await page.locator('#section-3 h3').innerText()).includes('2026-09-25'));
  await goto(3);
  await page.locator('[data-action="matrix-shop"][data-value="jd-b"]').click();
  await page.locator('#section-1 .chart [data-date="2026-09-25"]').click();
  await page.locator('#shop-select').selectOption('jd-a');
  check('Shop change clears old date/shop drill', await page.locator('#section-3 tbody [data-action="object-detail"]').count() > 0 && (await page.locator('#section-3 tbody').innerText()).includes('商用设备店'));
  const styles = await page.evaluate(() => ({ brand: getComputedStyle(document.documentElement).getPropertyValue('--brand').trim(),body: getComputedStyle(document.body).fontSize,kpi:getComputedStyle(document.querySelector('.kpi-value')).fontSize,title:getComputedStyle(document.querySelector('h1')).fontSize }));
  check('System colors and typography', styles.brand === '#396149' && styles.body === '14px' && styles.kpi === '24px' && styles.title === '20px', styles);
  await goto(1);
  await page.locator('#scenario-select').selectOption('misaligned');
  await page.locator('#shop-select').selectOption('jd-b');
  check('No ad records not zero-filled', (await overview())[0] === '—万元' && (await overview())[1] === '—万元');
  check('No ad records do not fabricate products', await page.locator('#section-3 tbody [data-action="object-detail"]').count() === 0);
  await goto(1);
  await page.locator('[data-action="calendar"]').click();
  await page.locator('[data-action="month"][data-value="-1"]').click();
  await page.locator('[data-calendar-date="2026-08-07"]').focus();
  await page.keyboard.press('Enter');
  await page.locator('[data-calendar-date="2026-08-13"]').focus();
  await page.keyboard.press('Enter');
  await page.locator('[data-action="calendar-apply"]').click();
  check('Calendar supports keyboard range selection', (await page.locator('.date-control').innerText()).includes('2026.08.07'));
  check('Incomplete base suppresses summary growth', (await page.locator('.kpi-foot').first().innerText()).includes('基期覆盖不足'));
  check('Incomplete base suppresses shop growth', !(await page.locator('#section-2 tbody').innerText()).includes('↑'));
  check('No runtime errors', errors.length === 0, errors);
  check('No business/external requests', requests.every(url => url.startsWith('http://127.0.0.1:3196/')), [...new Set(requests)]);
} finally {
  await browser.close();
  await writeFile(path.join(evidence, 'ui-checks.json'), JSON.stringify({ type:'synthetic-design-qa', checkedAt:new Date().toISOString(), productionValidated:false, checks, errors, requests:[...new Set(requests)] },null,2));
}
console.log(JSON.stringify({ checks:checks.length, passed:checks.every(check => check.ok),errors },null,2));
