"""Unregistered owning adapter for promotion file table materials.

Draft materials may precede model diagnosis; formal materials require current
ready content and the existing independent/human review validator. Nothing in
this module creates a file run or permits delivery without its final fence.
"""
from contextlib import contextmanager
from dataclasses import dataclass
import json

from business_analysis import promotion_report_tables
from business_analysis.contracts import AnalysisContractError
from . import business_promotion_runtime as runtime, business_promotion_export as export
from . import business_reports, models as m
from .policy import AiError, canonical, digest


@dataclass(frozen=True, slots=True)
class Metadata:
    _json: str

    @property
    def value(self): return json.loads(self._json)


def _conflict(message="推广文件材料与当前报告不一致"):
    raise AiError(message, "conflict", 409)


def _bound(report_id, principal, draft):
    fixed = runtime.bound_persisted(report_id, principal)
    if not draft:
        if fixed["contentReady"] is not True: _conflict("正式文件须等待词货内容完整就绪")
        report = m.AiReportRun.objects.select_related("workflow").get(pk=report_id)
        # Existing review machinery must explicitly support the new profile;
        # a ready screening or manually edited status cannot substitute for it.
        reviewed = business_reports.validate_review(report, principal)
        fixed = {**fixed, "reviewDigest": digest(reviewed)}
    return fixed


def _manifest(manifest, fixed):
    selector, roots = fixed["promotionSelector"], fixed["rootBindings"]
    if (manifest.get("manifestDigest") != digest({k:v for k,v in manifest.items() if k != "manifestDigest"})
        or manifest.get("sourceKey") != selector["sourceKey"]
        or manifest.get("baselineKey") != selector.get("baselineKey")):
        _conflict()
    actual = manifest["reportBinding"]
    expected = {k:fixed[k] for k in ("reportId", "workflowId", "snapshotDigest", "workflowInputDigest", "executionProfile")}
    expected.update({k:roots[k] for k in ("evidenceRunId", "evidenceVersion", "sealedDigest", "catalogDigest", "sourcesDigest")})
    if any(actual.get(k) != v for k,v in expected.items()): _conflict("导出材料不属于本次固定词货报告")


@contextmanager
def open_tables(report_id, principal, *, draft=False, checkpoint=None, limits=None):
    if type(draft) is not bool: raise AiError("草稿标志须为布尔值")
    fixed = _bound(report_id, principal, draft)
    selector = fixed["promotionSelector"]
    prepared = export.prepare(report_id, selector["sourceKey"], principal,
        baseline_key=selector.get("baselineKey"), checkpoint=checkpoint, limits=limits)
    if type(prepared) is not export.PreparedPromotionExport: _conflict("不能用公开DTO替代已完成推广材料")
    manifest = prepared.manifest
    try:
        _manifest(manifest, fixed)
        with promotion_report_tables.tables(manifest, {view: prepared.ndjson_pages(view) for view in export.VIEWS}) as (summary, tables):
            if canonical(_bound(report_id, principal, draft)) != canonical(fixed): _conflict()
            metadata = {"schemaVersion": "business-promotion-file-tables-v1", "draft": draft,
                "reportBinding": fixed, "materialManifestDigest": manifest["manifestDigest"],
                "sourceSummary": summary, "registeredRenderer": False, "deliveryAuthorized": False}
            metadata["metadataDigest"] = digest(metadata)
            yield Metadata(canonical(metadata)), tables
            # Caller must finish the context before publishing generated bytes.
            if canonical(_bound(report_id, principal, draft)) != canonical(fixed): _conflict("生成期间词货报告或复核状态已变化")
    except AnalysisContractError as error:
        raise AiError("完整词货文件表未通过无损校验", "conflict", 409) from error
