import {shops,products,createModel,aggregate,promotion,inventory,finance,escape,money,percent,addDays} from './shared/data.js';
import {createUI,titles} from './shared/ui.js';
import {detailScope} from './shared/scope.js';
const demos=[['01','均衡经营总览','结果在前，七域分区展开。每天快速查看经营全局。'],['02','章节式经营报告','沿结果、增长与质量逐章阅读，适合经营复盘。'],['03','多店经营对照矩阵','以店铺为行，用统一指标定位差异并展开对象证据。'],['04','图表与明细联动分屏','点击日期与店铺，同步查看局部证据及明细。'],['05','经营贡献探索','按平台、店铺、品类和ERP商品逐层探索可加总贡献。']];
const params=new URLSearchParams(location.search),saved=JSON.parse(sessionStorage.getItem('bi-demo-filters')||'null');
let state={demo:'01',start:'2026-09-01',end:'2026-09-30',platform:'',shop:'',grain:'week',compare:'previous',status:'ready',rank:'sales',allShops:false,qShop:'',qProduct:'',productFilter:'all',selectedShop:'',evidenceDate:'',exploreLevel:'platform',explorePlatform:'',exploreShop:'',exploreCategory:'',exploreMetric:'sales',...saved};
if(demos.some(x=>x[0]===params.get('demo')))state.demo=params.get('demo');
let layout=null,generation=0,returnFocus=null,modalScope=null;
const foldStates=new Map();let renderedDemo='';
const root=document.querySelector('#app'),dialog=document.querySelector('#detail');
const nav=[['BI 看板',''],['网店分析','?module=shop&view=analysis'],['市场分析','?module=market&view=ranking'],['销售分析','?module=sales&view=overview'],['客服分析','?module=customer_service&view=conversations'],['商品经营','?module=product&view=overview'],['库存管理','?module=inventory&view=overview'],['运营事务','?module=workflow&view=plan'],['自动化中心','?module=n8n_workflows&view=jackyun'],['数据导入','?module=import&view=files']];
const act=(a,v,l,c='')=>`<button class="${c}" data-action="${a}" data-value="${escape(v)}">${l}</button>`;
function select(label,field,options){return `<label>${label}<select data-field="${field}">${options.map(([v,l])=>`<option value="${escape(v)}" ${state[field]===v?'selected':''}>${escape(l)}</option>`).join('')}</select></label>`;}
function ctx(){const c={state,model:createModel(state),set,escape,money,percent};c.ui=createUI(c);return c;}
function set(patch){
 if('platform' in patch&&patch.platform!==state.platform){patch.shop='';patch.selectedShop='';patch.exploreLevel='platform';patch.explorePlatform='';patch.exploreShop='';patch.exploreCategory='';}
 if('shop' in patch&&patch.shop!==state.shop){patch.selectedShop='';patch.exploreLevel='platform';patch.explorePlatform='';patch.exploreShop='';patch.exploreCategory='';}
 if('start' in patch||'end' in patch||'grain' in patch)patch.evidenceDate='';
 state={...state,...patch};sessionStorage.setItem('bi-demo-filters',JSON.stringify(state));render();
}
function render(){
 for(const fold of root.querySelectorAll('#demo-body details'))foldStates.set(renderedDemo+'::'+(fold.id||fold.querySelector('summary')?.textContent),fold.open);
 const c=ctx(),d=demos.find(x=>x[0]===state.demo),m=c.model;
 const allowed=shops.filter(s=>!state.platform||s.platform===state.platform);
 const comparison=m.periods.baseline?`${state.compare==='year'?'同比去年同期':'环比等长前期'} ${m.periods.baseline.start}—${m.periods.baseline.end}`:'不比较';
 root.innerHTML=`<header class="masthead"><div class="brand">TERUISI <small>电商运营中台</small></div><nav class="nav" aria-label="应用导航（模拟）">${nav.map(([l,v])=>act(v?'module':'home',v,l,v?'':'active')).join('')}</nav><span class="demo-tag">合成数据 · 设计演示</span></header><nav class="demo-tabs" aria-label="五套Demo">${demos.map(([id,name])=>`<a class="${state.demo===id?'active':''}" href="?demo=${id}" data-demo="${id}" aria-current="${state.demo===id?'page':'false'}">${id} ${name}</a>`).join('')}</nav><main class="workspace"><div class="heading"><div><h1>综合经营驾驶舱 · ${d[1]}</h1><p class="intro">${d[2]}</p></div><div class="row">${act('guide','','五案对比与口径')}${act('references','','参考案例')}</div></div><section class="filters" aria-label="统一经营筛选"><label class="date-control">统计周期${act('date','',state.start+' — '+state.end)}</label>${select('平台','platform',[['','全部平台'],...Array.from(new Set(shops.map(s=>s.platform))).map(p=>[p,p])])}${select('店铺','shop',[['','全部店铺'],...allowed.map(s=>[s.id,s.name])])}${select('趋势粒度','grain',[['day','日'],['week','周（选期起点）'],['month','自然月']])}${select('比较方式','compare',[['previous','等长前期'],['year','去年同期'],['none','不比较']])}${act('reset','','重置筛选')}<div class="scenario">${select('演示状态','status',[['ready','正常（含真实缺源示例）'],['loading','加载中'],['error','加载失败'],['empty','ERP空数据'],['missing','推广来源缺失']])}</div></section><p class="period-note">本期 ${state.start}—${state.end} · ${comparison} · 示例今天 2026-10-05。${m.totals.comparable?'两期ERP店日完整。':'ERP比较覆盖不足时不展示百分比增幅。'} 公司库存与财报保留独立范围。</p><div id="demo-body" class="demo${state.demo}">${state.status==='loading'?'<div class="panel loading"><div><h2>正在读取合成示例…</h2><p>这是可检查的加载情景，筛选保持。</p>'+act('retry','','完成加载','primary')+'</div></div>':state.status==='error'?'<div class="panel empty"><h2>示例读取失败</h2><p>未展示旧范围数值。日期与平台筛选已保留。</p>'+act('retry','','重试读取','primary')+'</div>':layout?layout.render(c):'<div class="loading">正在加载设计方案…</div>'}</div><footer class="page-footer"><span>五案共享同一合成事实、口径和筛选 · Demo通过不等于真实数据或生产验收</span><span><a href="README.md" target="_blank">启动与交付说明</a> · <a href="RESEARCH.md" target="_blank">研究记录</a></span></footer></main>`;
 for(const fold of root.querySelectorAll('#demo-body details')){const key=state.demo+'::'+(fold.id||fold.querySelector('summary')?.textContent);if(foldStates.has(key))fold.open=foldStates.get(key);}renderedDemo=state.demo;
}
async function loadDemo(id){generation++;const token=generation;layout=null;state.demo=id;const css=document.querySelector('#layout-css')||Object.assign(document.createElement('link'),{id:'layout-css',rel:'stylesheet'});css.href=`demo${id}/layout.css`;if(!css.isConnected)document.head.append(css);render();try{const mod=await import(`./demo${id}/layout.js`);if(token!==generation)return;layout=mod;render();}catch(e){if(token!==generation)return;root.querySelector('#demo-body').innerHTML='<div class="panel warning">方案载入失败，请检查本地文件或刷新。</div>';console.error(e);}}
function openDetail(title,body){returnFocus=document.activeElement;dialog.innerHTML=`<div class="dialog-head"><div><small>合成演示详情 · 不连接正式接口</small><h2>${title}</h2></div>${act('close','','关闭详情')}</div><div class="stack">${body}</div><div class="dialog-return">${act('close','','返回驾驶舱（保留筛选）','primary')}</div>`;if(!dialog.open)dialog.showModal();}
function closeDetail(){dialog.close();modalScope=null;returnFocus?.isConnected&&returnFocus.focus();}
function moduleDetail(path){
 let scope=modalScope||{start:state.start,end:state.end,shop:state.shop||state.selectedShop,platform:state.platform};
 if(path.includes('module=inventory'))scope={...scope,start:inventory.demandStart,end:inventory.demandEnd,shop:'',platform:'',snapshot:inventory.snapshot};
 if(path.includes('view=finance'))scope={start:finance.month+'-01',end:finance.month+'-31',shop:'',platform:'',month:finance.month};
 const shop=shops.find(s=>s.id===scope.shop);
 openDetail('专业模块跳转演示',`<p>未来目标：<code>/${escape(path)}</code></p><div class="notice">${scope.product?'商品 '+escape(scope.product)+' · ':''}${shop?'精确店铺 '+escape(shop.name)+' · ':''}${scope.month?'公司完整财报月 '+scope.month:scope.snapshot?'公司库存快照 '+scope.snapshot+' · 需求窗口 '+scope.start+'—'+scope.end:'范围 '+scope.start+'—'+scope.end}。这里展示未来接线上下文，不打开生产页面。</div><p>正式实现复用现有导航契约，先复验身份、权限、来源和目标模块可接受参数。库存保留公司快照，财报保留自然月。</p><div class="fact"><span>已完成实际反馈</span><b>演示目标与携带筛选已生成</b><small>返回可继续当前设计比较</small></div>`);
}
function detailShop(id,source='global'){
 const shop=shops.find(s=>s.id===id);if(!shop)return;
 const scope=detailScope(state,ctx().model,source),r=createModel({...state,start:scope.start,end:scope.end,shop:id,platform:shop.platform}).totals;
 modalScope={...scope,shop:id,platform:shop.platform};
 openDetail(escape(shop.name),`<p>${shop.platform} · ERP精确演示ID ${id} · ${scope.start}—${scope.end}</p><div class="grid3"><div class="fact"><span>ERP净销售</span><b>${money(r.sales)}</b></div><div class="fact"><span>综合大毛利</span><b>${money(r.profit)}</b><small>${percent(r.margin)}</small></div><div class="fact"><span>广告归因成交</span><b>${money(r.attributed)}</b><small>ROAS ${r.roas===null?'未覆盖':r.roas.toFixed(2)+'倍'}</small></div></div><p class="notice">${shop.id==='s6'?'基期接入资格需按选期核验，不写“新增”。':shop.id==='s7'?'ERP未接入，不当零。':shop.id==='s8'?'完整覆盖、实际零成交；分母零的毛利率/ROAS不可用。':'销售和毛利分别核对，不能由销售增长推利润增长。'}</p><p>进入现有“网店分析 → 店铺全景”查看六源八章；平台成交仍独立于ERP净销售，库存及财报无本店可靠关联时停止拆解。</p>${act('module','?module=shop&view=analysis','进入店铺全景 · 模拟详情')}`);
}
function detailProduct(id,source='global'){
 const p=products.find(p=>p.id===id);if(!p)return;
 const scope=detailScope(state,ctx().model,source),m=createModel({...state,start:scope.start,end:scope.end,shop:scope.shop,platform:scope.platform});
 const r=aggregate(scope.start,scope.end,m.selectedShops,[p]);modalScope={...scope,product:id};
 openDetail(escape(p.name),`<p>ERP SKU ${id} · ${p.category} · ${scope.start}—${scope.end} · ${scope.shop?escape(shops.find(s=>s.id===scope.shop)?.name):'当前筛选范围'}</p><div class="grid3"><div class="fact"><span>净销售额</span><b>${money(r.sales)}</b></div><div class="fact"><span>综合大毛利</span><b>${money(r.profit)}</b></div><div class="fact"><span>毛利率</span><b>${percent(r.margin)}</b></div></div><p class="notice">库存按合成ERP编码可关联公司仓位；不将平台同名SKU/SPU直接拼接。${id==='K05'?'该商品一个仓位销量未匹配，库存需求无法完整验证。':''}</p><div class="table-scroll"><table><thead><tr><th>公司仓位</th><th>库存 / 风险</th><th>快照 / 需求</th></tr></thead><tbody>${inventory.items.filter(i=>i.id===id).map(i=>`<tr><td>${i.warehouse}</td><td>${i.qty} 件 / ${i.risk}</td><td>2026-10-01 / ${i.needed===null?'未匹配':i.needed+'件理论需求'}</td></tr>`).join('')}</tbody></table></div>${act('module','?module=product&view=overview','进入商品经营 · 模拟详情')}`);
}
function detailRisk(value){const [id,warehouse]=value.split('|'),r=inventory.items.find(r=>r.id===id&&r.warehouse===warehouse);if(!r)return;modalScope={start:inventory.demandStart,end:inventory.demandEnd,shop:'',product:id};openDetail(escape(r.name)+' · '+r.warehouse,`<div class="notice warning">${r.risk} · 快照2026-10-01已过期 · 需求窗口2026-09-05—2026-10-04</div><div class="grid2"><div class="fact"><span>货值 / 库龄</span><b>${money(r.value)}</b><small>${r.age} 天</small></div><div class="fact"><span>理论补货需求</span><b>${r.needed===null?'无法计算':r.needed+'件'}</b><small>有效补货暂停：先补新快照并复验销量关联</small></div></div><p>${r.matched?'销量已匹配；该需求仅理论缺口，不能作为采购指令。':'销量未匹配不属于零销量或低动销，不参与可靠补货。'}</p>${act('module','?module=inventory&view=plan','进入补货计划 · 模拟详情')}`);}
const references=[['Shopify 总览','https://help.shopify.com/en/manual/reports-and-analytics/shopify-reports/overview-dashboard/using-the-overview-dashboard','指标→趋势→报告；局部来源警告'],['Evidence 报告','https://docs.evidence.dev/core-concepts/markdown','章节叙述和图表共享查询变量'],['Power BI 矩阵','https://learn.microsoft.com/en-us/power-bi/visuals/power-bi-visualization-matrix-visual','店铺统一指标与层级矩阵'],['Metabase 联动','https://www.metabase.com/docs/latest/dashboards/interactive','点图更新筛选与记录证据'],['Superset 交叉筛选','https://superset.apache.org/','明确图表联动作用域'],['Power BI 分解树','https://learn.microsoft.com/en-us/power-bi/visuals/power-bi-visualization-decomposition-tree','贡献路径和分支返回']];
function dispatch(a,v,scopeElement){const c=ctx();if(layout?.onAction?.(a,v,c))return;
 const source=scopeElement?.closest('[data-evidence-scope],.evidence')?'local':a==='explore-product'?'explore':'global';
 if(a==='close')return closeDetail();if(a==='module')return moduleDetail(v);if(a==='detail-shop')return detailShop(v,source);if(a==='detail-product'||a==='explore-product')return detailProduct(v,source);if(a==='detail-risk')return detailRisk(v);
 if(a==='home'){closeDetail();return window.scrollTo({top:0,behavior:'smooth'});}if(a==='all-shops')return set({allShops:!state.allShops});if(a==='select-shop')return set({selectedShop:v});if(a==='select-date')return set({evidenceDate:v});if(a==='reset-evidence')return set({evidenceDate:'',selectedShop:''});if(a==='retry')return set({status:'ready'});
 if(a==='section'){document.getElementById(v)?.scrollIntoView({behavior:'smooth',block:'start'});return;}
 if(a==='explore-platform')return set({explorePlatform:v,exploreLevel:'shop',exploreShop:'',exploreCategory:''});if(a==='explore-shop')return set({exploreShop:v,exploreLevel:'category',exploreCategory:'',selectedShop:v});if(a==='explore-category')return set({exploreCategory:v,exploreLevel:'product'});if(a==='explore-reset')return set({exploreLevel:'platform',explorePlatform:'',exploreShop:'',exploreCategory:'',selectedShop:''});if(a==='explore-up'){if(state.exploreLevel==='product')return set({exploreLevel:'category',exploreCategory:''});if(state.exploreLevel==='category')return set({exploreLevel:'shop',exploreShop:'',selectedShop:''});return set({exploreLevel:'platform',explorePlatform:'',exploreShop:'',exploreCategory:''});}
 if(a==='reset')return set({start:'2026-09-01',end:'2026-09-30',platform:'',shop:'',grain:'week',compare:'previous',status:'ready',rank:'sales',allShops:false,qShop:'',qProduct:'',productFilter:'all',selectedShop:'',evidenceDate:'',exploreLevel:'platform',explorePlatform:'',exploreShop:'',exploreCategory:'',exploreMetric:'sales',matrixMode:'shops',linkedView:'trend',linkedProduct:''});
 if(a==='date')return window.comparisonDatePicker.open({label:'统计周期 · 复用定版日期控件',startDate:state.start,endDate:state.end,minDate:'2025-01-01',maxDate:'2026-10-04',maxDays:366,onApply:(start,end)=>set({start,end})});
 if(a==='references')return openDetail('真实调研来源',`<div class="link-list">${references.map(([name,url,why])=>`<div><a href="${url}" target="_blank" rel="noopener">${name} ↗</a><small>${why}</small></div>`).join('')}</div><p>全部自行实现，无第三方UI代码复制。MIT / Apache / AGPL与商业许可边界见 <a href="RESEARCH.md" target="_blank">完整研究记录</a>；部分页面访问限制也已记录。</p>`);
 if(a==='guide')return openDetail('五案选择与统一口径',`<div class="table-scroll"><table><thead><tr><th>编号</th><th>组织与用途</th><th>代价</th></tr></thead><tbody>${demos.map(([id,name,desc])=>`<tr><td>${id} ${name}</td><td>${desc}</td><td>${id==='01'?'快速直观，长页面，中等':id==='02'?'阅读充分，日看较慢，中等':id==='03'?'横向比较强，窄屏需横滚，较高':id==='04'?'证据联动强，选择规则较复杂，较高':'拆解清楚，身份依赖最多，较高'}</td></tr>`).join('')}</tbody></table></div><p>推荐01作为日常入口：经营结果先行，七域完整且复用现有专业模块最直接。若日常以多店差异排查为主，可选03或04。</p><p>综合大毛利＝ERP净销售−成本；退货比例＝退货金额/正向销售；ROAS＝归因成交/推广花费。金额不混加，率按汇总分子分母。所有状态与数字均为合成演示。</p>`);
}
document.addEventListener('click',e=>{const d=e.target.closest('[data-demo]');if(d){e.preventDefault();history.replaceState({},'',`?demo=${d.dataset.demo}`);sessionStorage.setItem('bi-demo-filters',JSON.stringify({...state,demo:d.dataset.demo}));loadDemo(d.dataset.demo);return;}const b=e.target.closest('[data-action]');if(b)dispatch(b.dataset.action,b.dataset.value||'',b);});
document.addEventListener('change',e=>{const el=e.target.closest('[data-field]');if(el)set({[el.dataset.field]:el.value});});
document.addEventListener('keydown',e=>{if(e.target.matches('circle[data-action]')&&(e.key==='Enter'||e.key===' ')){e.preventDefault();dispatch(e.target.dataset.action,e.target.dataset.value);}});
dialog.addEventListener('cancel',e=>{e.preventDefault();closeDetail();});
loadDemo(state.demo);
