import {createPanels} from './panels.js';
import {AS_OF,TODAY,shops,getRange,buildModel} from './model.js';
import {escape as esc,addDays,dayCount} from '../shared/data.js';

const root=document.querySelector('#app'), dialog=document.querySelector('#detail');
const KEY='teruisi-bi-reference-simple-v2';
const sections=[['targets','项目年 / 月目标'],['todos','待处理事项'],['sales','销售经营'],['shops','店铺同比下滑'],['categories','类目经营表现'],['customer','客服接待'],['supply','备货与入仓'],['inventory','库存健康'],['traffic','网店流量与转化'],['products','商品表现'],['promotion','推广效率'],['finance','月度财报']];
const initial={period:'month',start:'2026-10-01',end:AS_OF,platform:'',shop:'',scenario:'normal',mine:false,shopMode:'declines',flowPlatform:'',flowShop:'',flowDimension:'shop',metric:'sales',grain:'day',hidden:['customer','supply','products','promotion','finance']};
let saved={};try{saved=JSON.parse(sessionStorage.getItem(KEY)||'{}')||{};}catch{}
let state={...initial,...saved};
if(!['month','last30','last7','custom'].includes(state.period))state.period='month';
if(!shops.some(s=>s.id===state.shop))state.shop='';
if(!Array.isArray(state.hidden))state.hidden=initial.hidden;
state.hidden=state.hidden.filter(k=>sections.some(([id])=>id===k));
if(!['normal','missing','empty'].includes(state.scenario))state.scenario='normal';
if(!['sales','profit'].includes(state.metric))state.metric='sales';
if(!['day','week'].includes(state.grain))state.grain='day';
try{getRange(state.period,state);}catch{state.period=initial.period;state.start=initial.start;state.end=initial.end;}
let model,chartPoint=null,returnFocus=null,toastTimer;
const icons={filter:'<path d="M3 4h18l-7 8v6l-4 2v-8z"/>',settings:'<path d="M4 7h16M4 17h16"/><circle cx="9" cy="7" r="3"/><circle cx="15" cy="17" r="3"/>',calendar:'<rect x="3" y="5" width="18" height="16" rx="2"/><path d="M7 3v5m10-5v5M3 11h18"/>',arrow:'<path d="M5 12h14m-5-5 5 5-5 5"/>'};
const icon=n=>`<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" aria-hidden="true">${icons[n]||icons.arrow}</svg>`;
const num=(v,d=0)=>v==null||!Number.isFinite(v)?'—':Number(v).toLocaleString('zh-CN',{minimumFractionDigits:d,maximumFractionDigits:d});
const amt=v=>v==null||!Number.isFinite(v)?'—':Math.abs(v)>=10000?num(v/10000,2)+'<span class="unit">万</span>':num(v,2);
const money=v=>v==null?'—':Math.abs(v)>=10000?num(v/10000,2)+' 万元':num(v,2)+' 元';
const wan=v=>v==null?'—':num(v/10000,2)+' 万';
const pct=(v,d=1)=>v==null||!Number.isFinite(v)?'—':num(v*100,d)+'%';
const ratio=(a,b)=>a==null||b==null||b<=0?null:a/b;
const cmp=(a,b)=>a==null||b==null||b<=0?null:(a-b)/Math.abs(b);
const signed=(n,d=1)=>{if(n==null)return '—';const rounded=Number(n.toFixed(d));return (rounded>0?'+':rounded<0?'−':'')+num(Math.abs(rounded),d);};
const delta=(a,b,kind='percent')=>{const v=kind==='pp'?(a==null||b==null?null:(a-b)*100):kind==='abs'?(a==null||b==null?null:a-b):cmp(a,b);return v==null?'<span class="muted">暂无可比数据</span>':`<span class="${v>0?'up':v<0?'down':'muted'}">${signed(kind==='percent'?v*100:v)}${kind==='pp'?'pt':kind==='percent'?'%':''}</span>`;};
const action=(a,label,value='',cls='text-btn',extra='')=>`<button type="button" class="${cls}" data-action="${a}" data-value="${esc(value)}" ${extra}>${label}</button>`;
const info=key=>action('help','?',key,'help-btn',`aria-label="查看${esc(key)}口径"`);
const compact=s=>s.compactName||s.name.replace('TERUISI ','').replace('（长名称示例）','');
const visible=k=>!state.hidden.includes(k);
function heading(title,sub,detail,label='查看详情'){return `<div class="card-head"><div class="card-title"><h2>${title}</h2>${sub?`<small>${sub}</small>`:''}</div>${detail?action('detail',`${label} <span aria-hidden="true">›</span>`,detail):''}</div>`;}
function metric(label,value,a,b,kind='percent',options={}){return `<${options.select?'button type="button"':'div'} class="metric ${options.select&&state.metric===options.select?'is-active':''}" ${options.select?`data-action="metric" data-value="${options.select}"`:''}><span class="metric-label">${label}</span><strong class="metric-value">${value}</strong><div class="metric-compare"><span>环比 ${delta(a,b,kind)}</span>${options.year!==undefined?`<span>同比 ${delta(a,options.year,kind)}</span>`:''}</div>${options.note?`<p class="metric-info">${options.note}</p>`:''}</${options.select?'button':'div'}>`;}
const empty=text=>`<div class="empty-state">${text}</div>`;
const panels=()=>createPanels({state,model,action,heading,amt,wan,pct,num,delta,money,esc,table,empty,metric});
function monthCard(){return panels().goalCard();}
function todoDescription(t){return ({inbound:'库存管理 · 入仓计划',operations:'运营事务 · 工作计划',plan:'运营事务 · 工作计划',replenishment:'库存管理 · 备货草稿',mapping:'库存管理 · 销量关联',review:'运营事务 · 评价维护',reviews:'运营事务 · 评价维护',target:'销售分析 · 月目标',coverage:'数据导入 · 来源检查'})[t.id]||t.scope||'相关经营事项';}
function todosCard(){return panels().todosCard();}
function chart(width=900){const metricKey=state.metric;let rows=model.sales.trend||[];if(state.grain==='week'){const grouped=[];for(let i=0;i<rows.length;i+=7){const part=rows.slice(i,i+7);grouped.push({date:part[0].date,end:part.at(-1).date,value:part.reduce((n,r)=>n+(r.value??0),0),previous:part.some(r=>r.previous==null)?null:part.reduce((n,r)=>n+r.previous,0),profit:part.reduce((n,r)=>n+(r.profit??0),0),previousProfit:part.some(r=>r.previousProfit==null)?null:part.reduce((n,r)=>n+r.previousProfit,0)});}rows=grouped;}
 if(!rows.length||model.sales.current.sales==null)return empty('当前期间没有销售数据');
 const points=rows.map(r=>({...r,v:metricKey==='profit'?r.profit:r.value,p:metricKey==='profit'?r.previousProfit:r.previous}));
 const W=Math.max(280,Math.round(width)),H=225,L=48,R=12,T=17,B=30,innerW=W-L-R,innerH=H-T-B,vals=points.flatMap(p=>[p.v,p.p]).filter(Number.isFinite),rawMax=Math.max(1,...vals),rawMin=Math.min(0,...vals),spread=rawMax-rawMin;
 const max=rawMax+spread*.12,min=rawMin<0?rawMin-spread*.08:0,y=v=>T+(max-v)/(max-min)*innerH,step=innerW/points.length,bw=Math.min(32,step*.48),x=i=>L+step*(i+.5),zero=y(0),ticks=[max,max*.5,0,...(min<0?[min]:[])];
 const pathParts=[];let pen=false;points.forEach((p,i)=>{if(p.p==null){pen=false;return;}pathParts.push(`${pen?'L':'M'}${x(i).toFixed(2)},${y(p.p).toFixed(2)}`);pen=true;});
 const labelStep=Math.max(1,Math.ceil(points.length/Math.max(3,Math.floor(W/90))));
 const currentPoint=points.find(p=>p.date===chartPoint);
 return `<div class="sales-chart"><svg viewBox="0 0 ${W} ${H}" preserveAspectRatio="none" role="img" aria-label="${metricKey==='profit'?'综合大毛利':'净销售'}与前期同位日对比，金额单位元"><g>${ticks.map(v=>`<line class="${v===0?'zero-line':'grid-line'}" x1="${L}" y1="${y(v)}" x2="${W-R}" y2="${y(v)}"/><text x="${L-8}" y="${y(v)+4}" text-anchor="end">${Math.abs(v)>=10000?num(v/10000,1)+'万':num(v)}</text>`).join('')}</g>${points.map((p,i)=>`<rect class="bar ${p.v<0?'negative':''} ${p.date===chartPoint?'selected':''}" x="${x(i)-bw/2}" y="${Math.min(zero,y(p.v??0))}" width="${bw}" height="${p.v===0||p.v==null?0:Math.max(1,Math.abs(zero-y(p.v)))}" rx="1" tabindex="0" role="button" data-action="point" data-value="${p.date}" aria-label="查看 ${p.date} ${metricKey==='profit'?'毛利':'销售'} ${num(p.v,2)}元"><title>${p.date}${p.end?'—'+p.end:''}\n本期 ${money(p.v)}\n前期 ${money(p.p)}</title></rect>${i%labelStep===0||i===points.length-1?`<text x="${x(i)}" y="${H-7}" text-anchor="middle">${p.date.slice(5)}</text>`:''}`).join('')}<path class="prior-line" d="${pathParts.join(' ')}"/></svg></div><div class="chart-foot"><span class="chart-value" id="chart-selection">${currentPoint?`${currentPoint.date}${currentPoint.end?'—'+currentPoint.end:''} · 本期 ${money(currentPoint.v)} · 前期 ${money(currentPoint.p)}`:'点击柱形查看数值'}</span><span>金额单位：元</span></div>`;
}
function salesCard(){const c=model.sales.current,p=model.sales.previous||{},y=model.sales.yearAgo||{};return `<article class="card span2 sales-card" data-section="sales">${heading('销售','ERP 净额口径','sales','进入销售总览')}<div class="metrics">${metric('净销售额',amt(c.sales),c.sales,p.sales,'percent',{select:'sales',year:y.sales})}${metric('综合大毛利',amt(c.profit),c.profit,p.profit,'percent',{select:'profit',year:y.profit})}${metric('大毛利率',pct(c.margin),c.margin,p.margin,'pp',{year:y.margin})}${metric('退货率（金额）',pct(c.returnRate),c.returnRate,p.returnRate,'pp',{year:y.returnRate})}${metric('客单价',amt(c.averageOrderValue),c.averageOrderValue,p.averageOrderValue,'percent',{year:y.averageOrderValue,note:'ERP净销售 ÷ 可信订单'})}</div><div class="chart-top"><div class="chart-legend"><span><i class="legend-swatch"></i>${state.metric==='profit'?'综合大毛利':'净销售额'}</span><span><i class="legend-dashed"></i>前期同位${state.grain==='week'?'周期':'日'}</span></div><div class="segmented compact" aria-label="趋势粒度">${action('grain','日','day',state.grain==='day'?'active':'')}${action('grain','每 7 天','week',state.grain==='week'?'active':'')}</div></div><div class="trend-render">${chart()}</div></article>`;}
function shopCard(){return panels().shopCard();}
function customerCard(){const c=model.customer,p=c.previous||{};return `<article class="card" data-section="customer">${heading('客服接待','已导入会话','customer','进入客服分析')}<div class="metrics two">${metric('已分析会话',num(c.conversations),c.conversations,p.conversations)}${metric('问题会话占比',pct(c.issueRate),c.issueRate,p.issueRate,'pp')}${metric('平均首次响应',`${num(c.responseSeconds,1)}<span class="unit">秒</span>`,c.responseSeconds,p.responseSeconds,'abs')}${metric('覆盖店铺',`${c.conversations==null?'—':num(c.shops.length)}<span class="unit">家</span>`,c.conversations==null?null:c.shops.length,p.conversations==null?null:p.shops?.length,'abs')}</div><p class="card-note inline">成交归因未接通，先看接待质量。${action('help','查看口径','客服接待')}</p></article>`;}
function supplyCard(){const s=model.supply;return `<article class="card" data-section="supply">${heading('备货与入仓','当前计划','supply','进入库存管理')}<div class="metrics two"><div class="metric"><span class="metric-label">待确认备货</span><strong class="metric-value">${num(s.draft)}<span class="unit">项</span></strong><p class="metric-info">确认后进入执行</p></div><div class="metric"><span class="metric-label">执行中计划</span><strong class="metric-value">${num(s.confirmed)}<span class="unit">项</span></strong><p class="metric-info">已确认，尚未完成</p></div><div class="metric"><span class="metric-label">待入库数量</span><strong class="metric-value">${num(s.inboundUnits)}<span class="unit">件</span></strong><p class="metric-info">来自已有备货计划</p></div><div class="metric"><span class="metric-label">延期计划</span><strong class="metric-value ${s.delayed?'warn':''}">${num(s.delayed)}<span class="unit">项</span></strong><p class="metric-info">需核对预计到货日</p></div></div><p class="card-note inline">延续现有备货流程，采购实收指标待补源。</p></article>`;}
function stockCard(){const i=model.inventory;return `<article class="card stock-card" data-section="inventory">${heading('库存健康',`快照 ${i.snapshot.slice(5)} · 公司库存`,'inventory','进入库存总览')}<div class="stock-value"><strong>${amt(i.value)}</strong><small>公司库存总额 · 销量已匹配 ${pct(1-ratio(i.unmatchedValue,i.value))} 货值</small></div><div class="stock-bar" aria-label="库存金额按覆盖天数分档">${i.buckets.map((b,index)=>`<button style="width:${(ratio(b.value,i.value)||0)*100}%;background:${b.color}" title="${esc(b.label)} ${pct(ratio(b.value,i.value))}" aria-label="${esc(b.label)}：${money(b.value)}" data-action="stock-bucket" data-value="${index}"></button>`).join('')}</div><div class="stock-legend">${i.buckets.map((b,index)=>action('stock-bucket',`<i style="background:${b.color}"></i>${esc(b.label)} ${pct(ratio(b.value,i.value),1)}`,index,'')).join('')}</div><button class="stock-risk" data-action="detail" data-value="inventory"><strong>${pct(i.riskShare,0)}</strong> 库存货值覆盖超 90 天或近 30 天无销量 <span class="chevron">›</span></button><p class="stock-unknown">销量未匹配 ${money(i.unmatchedValue)}，单独列示。${action('help','口径','库存健康')}</p>${panels().guangdongSummary()}</article>`;}
function productsCard(){const rows=[...model.products].sort((a,b)=>(b.sales||0)-(a.sales||0)).slice(0,3);return `<article class="card" data-section="products">${heading('商品表现','销售贡献前 3','products','查看全部商品')}<div class="table-wrap"><table class="compact-table"><thead><tr><th>商品</th><th>净销售</th><th>毛利率</th></tr></thead><tbody>${rows.map(p=>`<tr><td>${action('product',esc(p.name),p.id)}<small>${esc(p.category)}</small></td><td>${wan(p.sales)}</td><td class="${p.margin<0?'up':''}">${pct(p.margin)}</td></tr>`).join('')}</tbody></table></div><p class="card-note inline">${model.products.some(p=>p.profit<0)?`${model.products.filter(p=>p.profit<0).length} 款商品毛利为负，建议关注。`:'同一期间的 ERP 商品贡献。'} ${action('detail','查看毛利明细','products')}</p></article>`;}
function promotionCard(){const p=model.promotion,prev=p.previous||{};return `<article class="card" data-section="promotion">${heading('推广效率','同一归因口径','promotion','进入推广分析')}<div class="mini-metrics">${metric('推广花费',amt(p.spend),p.spend,prev.spend)}${metric('推广成交',amt(p.attributed),p.attributed,prev.attributed)}${metric('推广 ROI',`${num(p.roas,2)}<span class="unit">倍</span>`,p.roas,prev.roas,'abs')}</div><div class="divider"></div><div class="stock-value"><small>推广占平台成交</small><strong style="font-size:20px">${pct(p.adRate,2)}</strong></div><p class="card-note inline">ROI 为广告归因成交 ÷ 花费，不代表利润率。</p></article>`;}
function financeCard(){const f=model.finance;return `<article class="card" data-section="finance">${heading('月度财报',`${f.month} · ${f.status}`,'finance','进入财报分析')}<div class="mini-metrics"><div class="metric"><span class="metric-label">财报利润</span><strong class="metric-value">${amt(f.profit)}</strong><div class="metric-compare">环比 ${delta(f.profit,f.previousProfit)}</div></div><div class="metric"><span class="metric-label">利润目标</span><strong class="metric-value">${amt(f.target)}</strong><p class="metric-info">公司完整月</p></div><div class="metric"><span class="metric-label">目标完成率</span><strong class="metric-value">${pct(ratio(f.profit,f.target))}</strong><p class="metric-info">已完成财报口径</p></div></div><div class="finance-progress"><div class="progress-track"><i class="progress-fill" style="width:${Math.min(100,(ratio(f.profit,f.target)||0)*100)}%"></i></div><span>${pct(ratio(f.profit,f.target))}</span></div><p class="card-note inline">独立完整月，不随上方经营日范围变化。</p></article>`;}
function render(){model=buildModel(state);const r=model.range,m=model.month;const cards=[['categories',()=>panels().categoriesCard()],['customer',customerCard],['supply',supplyCard],['inventory',stockCard],['traffic',()=>panels().trafficCard()],['products',productsCard],['promotion',promotionCard],['finance',financeCard]];
root.innerHTML=`<header class="app-top"><div class="brand">TERUISI</div><nav class="app-nav" aria-label="系统导航">${['BI 看板','网店分析','市场分析','销售分析','客服分析','商品经营','库存管理','运营事务','自动化中心','数据导入'].map((n,i)=>action(i?'module':'home',n,n,i?'':'active')).join('')}</nav><span class="preview-label">设计预览 · 示例数据</span><span class="avatar" aria-label="管理视角">管</span></header><main class="shell"><div class="page-heading"><div><h1>BI 看板 <span class="mobile-preview badge">示例预览</span></h1><div class="page-meta"><span>经营数据截至 <strong>${AS_OF.slice(5)}（周日）</strong></span><span>· 本月时间进度 <strong>${pct(m.pace,0)}</strong></span><span class="mini-pace" aria-hidden="true"><i style="width:${m.pace*100}%"></i></span><span>（${m.daysElapsed} / ${m.daysTotal} 天）</span></div></div><div class="controls"><div class="segmented" role="group" aria-label="经营周期">${[['month','本月'],['last30','近 30 天'],['last7','近 7 天']].map(([v,l])=>action('period',l,v,state.period===v?'active':'',`aria-pressed="${state.period===v}"`)).join('')}${action('date',state.period==='custom'?'已选日期':'自定义','',state.period==='custom'?'active':'')}</div>${action('filter',icon('filter')+' 筛选','','control-btn')}${action('customize',icon('settings')+' 自定义看板','','control-btn')}</div></div>${state.shop||state.platform?`<div class="filter-summary"><span>当前范围</span>${action('filter',esc(state.shop?compact(shops.find(s=>s.id===state.shop)):state.platform))}${action('clear-filter','清除筛选')}</div>`:''}<section class="dashboard-grid" aria-label="目标与待办">${visible('targets')?monthCard():''}${visible('todos')?todosCard():''}</section><div class="section-heading"><div><h2>${r.label}经营</h2><small>${r.start.slice(5)} — ${r.end.slice(5)} · 对比前 ${dayCount(r.start,r.end)} 天（${r.previousStart.slice(5)} — ${r.previousEnd.slice(5)}）</small></div><div class="status-line"><i class="dot" style="${state.scenario==='normal'?'':'background:var(--color-warning)'}"></i>${action('sources',state.scenario==='normal'?'数据来源与口径':'存在来源缺口 · 查看')}</div></div><section class="dashboard-grid" aria-label="经营情况">${visible('sales')?salesCard():''}${visible('shops')?shopCard():''}${cards.filter(([k])=>visible(k)).map(([,f])=>f()).join('')}</section><footer class="footer"><span>公司经营总览 · 目标看本月，经营看选期，库存看快照</span><div class="footer-actions">${action('more','更多经营信息')}${action('sources','数据来源')}${action('about','本版调整说明')}${action('scenario','演示设置')}<a href="../index.html">原五套 Demo</a></div></footer></main>`;
 const chartHost=root.querySelector('.trend-render');if(chartHost)chartHost.innerHTML=chart(chartHost.clientWidth);
}
function set(patch){state={...state,...patch};if(patch.platform!==undefined&&patch.platform!==initial.platform&&state.shop&&!shops.some(s=>s.id===state.shop&&s.platform===patch.platform))state.shop='';if(['platform','shop'].some(key=>key in patch)){state.flowPlatform='';state.flowShop='';}if(['platform','shop','period','start','end','metric','grain'].some(key=>key in patch))chartPoint=null;sessionStorage.setItem(KEY,JSON.stringify(state));render();}
function open(title,body){returnFocus=document.activeElement;dialog.innerHTML=`<div class="dialog-head"><h2 id="detail-title">${title}</h2>${action('close','×','','close-btn','aria-label="关闭详情"')}</div><div class="dialog-body">${body}<div class="dialog-actions">${action('close','返回看板','','control-btn')}</div></div>`;if(!dialog.open)dialog.showModal();dialog.querySelector('.close-btn').focus();}
function close(){dialog.close();if(returnFocus?.isConnected)returnFocus.focus();}
function table(headers,rows){return `<div class="table-wrap"><table><thead><tr>${headers.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map(c=>`<td>${c}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;}
const detailMetric=(label,value)=>`<div class="detail-metric"><span>${label}</span><strong>${value}</strong></div>`;
const sourceIntro=()=>`<p class="muted small">设计演示 · 以下均为合成数据。正式功能将复用现有专业模块，尚未连接真实业务接口。</p>`;
function detail(key){const r=model.range,c=model.sales.current;let title,body;
 switch(key){
 case 'targets':{const view=panels().detail('targets');title=view.title;body=view.body;}break;
 case 'todos':{const view=panels().detail('todos');title=view.title;body=view.body;}break;
 case 'sales':title='销售经营明细';body=`${sourceIntro()}<p>${r.start} — ${r.end} · ERP 净额口径</p>${detailMetric('净销售额',money(c.sales))}${detailMetric('综合大毛利',money(c.profit))}${detailMetric('大毛利率',pct(c.margin))}${detailMetric('退货金额',money(c.returns))}${detailMetric('可信ERP订单数',num(c.orders))}${detailMetric('客单价（净额/订单）',money(c.averageOrderValue))}${table(['日期','净销售额','大毛利','前期同位日'],model.sales.trend.map(x=>[x.date,money(x.value),money(x.profit),money(x.previous)]))}<p class="small muted">正式目标页面：销售分析 → 销售总览，保留日期、平台与店铺条件。</p>`;break;
 case 'shopPerformance':case 'categories':case 'guangdong':case 'traffic':{const view=panels().detail(key);title=view.title;body=view.body;}break;
 case 'customer':title='客服接待质量';body=`${sourceIntro()}<p>${r.start} — ${r.end} · 已导入和已分析会话范围</p>${detailMetric('已分析会话',num(model.customer.conversations))}${detailMetric('问题会话占比',pct(model.customer.issueRate))}${detailMetric('平均首次响应',num(model.customer.responseSeconds,1)+' 秒')}${detailMetric('覆盖店铺',(model.customer.conversations==null?'—':num(model.customer.shops.length))+' 家')}<p class="card-note">我们的现有会话标注不能直接证明订单成交归因，所以本版没有照搬参考页的客服成交额与询单转化率。</p><p class="small muted">正式目标页面：客服分析 → 会话与聊天分析。</p>`;break;
 case 'supply':title='备货与入仓';body=`${sourceIntro()}${Object.entries({待确认备货:model.supply.draft,执行中计划:model.supply.confirmed,待入库件数:model.supply.inboundUnits,延期计划:model.supply.delayed}).map(([k,v])=>detailMetric(k,num(v))).join('')}<p class="card-note">采购金额、采购单实收率不是现有备货计划的同义指标。正式接入以现有计划状态、数量和日期为准，不从销售额反推。</p><p class="small muted">正式目标页面：库存管理 → 备货计划 / 入仓管理。</p>`;break;
 case 'inventory':title='库存健康与风险';body=`${sourceIntro()}<p>公司库存快照 ${model.inventory.snapshot}；需求窗口 ${model.inventory.demandStart} — ${model.inventory.demandEnd}。不按店铺任意分摊。</p>${detailMetric('库存货值',money(model.inventory.value))}${detailMetric('覆盖超90天或无销量货值',money(model.inventory.riskValue))}${detailMetric('销量未匹配货值',money(model.inventory.unmatchedValue))}${table(['分档','货值','占库存货值'],model.inventory.buckets.map(b=>[esc(b.label),money(b.value),pct(ratio(b.value,model.inventory.value))]))}${table(['商品 / 仓','库存','可售天数','货值'],model.inventory.items.map(p=>[esc(p.name)+'<small>'+esc(p.warehouse)+'</small>',num(p.qty),p.noSales?'近30日无销量':!p.matched?'未匹配':p.days==null?'不可计算':num(p.days,1),money(p.value)]))}<p class="small muted">正式目标页面：库存管理 → 总览 / 库龄 / 滞销库存。按可售天数分档，不是财务平均库存周转率。整体存在销量未匹配时，不给出完整公司覆盖天数。</p>`;break;
 case 'products':title='商品经营表现';body=`${sourceIntro()}<p>${r.start} — ${r.end} · ERP SKU</p>${table(['商品','净销售','大毛利','毛利率','销售变化'],model.products.map(p=>[esc(p.name),money(p.sales),money(p.profit),pct(p.margin),p.change==null?'暂无可比数据':signed(p.change*100)+'%']))}<p class="small muted">正式目标页面：商品经营，按 ERP 商品身份进入详情。</p>`;break;
 case 'promotion':title='推广投入与效率';body=`${sourceIntro()}<p>${r.start} — ${r.end} · 同期平台推广来源</p>${detailMetric('推广花费',money(model.promotion.spend))}${detailMetric('广告归因成交',money(model.promotion.attributed))}${detailMetric('ROI / ROAS',num(model.promotion.roas,2)+' 倍')}${table(['店铺','推广花费','归因成交','ROI'],model.promotion.rows.map(s=>[esc(compact(s)),money(s.spend??s.adSpend),money(s.attributed),num(s.roas,2)]))}<p>ROI 在此沿用现有界面名称，含义是广告归因成交÷花费。不同来源的归因窗口正式接入时分别标注，不能当利润率或增量收益。</p><p class="small muted">正式目标页面：网店分析 → 推广分析。</p>`;break;
 case 'finance':{const f=model.finance;title='月度财报';body=`${sourceIntro()}<p>${f.month} · ${f.status} · 公司完整月</p>${detailMetric('财报净销售',money(f.revenue))}${detailMetric('财报利润',money(f.profit))}${detailMetric('同口径月利润目标',money(f.target))}${table(['费用','本月','前月'],f.expenses.map(e=>[esc(e.name),money(e.value),money(e.previous)]))}<p class="small muted">正式目标页面：销售分析 → 财报分析。月度费用不拆成日利润。</p>`;break;}
 default:title='经营详情';body=sourceIntro();}
 open(title,body);
}
function shopDetail(id){const s=model.shopPerformance.find(x=>x.id===id),m=model.goals.rows.find(x=>x.id===id);if(!s)return;open(esc(compact(s)),sourceIntro()+'<p class="small muted">经营期间 '+model.range.start+' — '+model.range.end+'</p>'+detailMetric('本期净销售',money(s.sales))+detailMetric('去年同日期净销售',money(s.yearAgo))+detailMetric('同比增减额',money(s.deltaYoy))+detailMetric('同比变化',s.yoy==null?'暂无可比数据':signed(s.yoy*100)+'%')+detailMetric('环比变化',s.mom==null?'暂无可比数据':signed(s.mom*100)+'%')+'<h3>固定本月目标</h3>'+detailMetric('月目标',money(m?.target))+detailMetric('月累计净销售',money(m?.sales))+detailMetric('月目标完成率',pct(m?.completion))+'<p class="card-note">正式进入店铺全景时保留当前店铺与日期；关闭后返回原筛选。</p>');}
const definitions={
 '客单价':'本版采用同范围ERP净销售÷可信ERP订单数，订单身份按店铺/来源去重。现有销售分析的旧客单价字段实际按剔除配件净销售÷净销量计算；正式接线会明确两种口径，不直接混用。',
 '店铺同比下滑':'只比较同店铺、去年同日期的ERP净销售。同比小于0列入下滑；≤-10%重点关注，≤-20%严重。未知、零或负基期不计算百分比，也不当作新增或健康。',
 '流量与转化':'访客数按商品×日累计；累计成交客户与访客同粒度求和后计算转化率，不能解释为店铺去重 UV。推广占比为同一店铺、同一期的推广花费÷平台成交额。',
 '客服接待':'已分析会话和问题会话比例来自会话质检；平均首次响应来自具有有效时间戳的会话。这里不使用未验证的客服订单归因或人工“已转化”标签估算成交额。',
 '库存健康':'按当前公司快照货值分档。无销量与销量未匹配分别展示。风险占比只包括已确定的高覆盖天数和无销量库存；未匹配货值仍在总库存分母中，另外列示。图中分档为库存预测覆盖天数，正式计算规则需要与库存模块统一。',
};
function sources(){open('数据来源与口径',`${sourceIntro()}${[['ERP 销售','销售分析 / ERP 销售权威数据','可复用。大毛利额与率使用相同分子，不与现有扣费用的订单毛利混配。'],['月目标','现有财报目标模型＋同口径销售累计','需确认目标期间、店铺映射与 ERP 口径。本页为独立合成月目标。'],['平台与推广','网店商品日数据、推广日数据','需同店同日关联与覆盖校验；商品访客累计不是去重 UV。'],['客服接待','会话与聊天分析','接待与质检可复用，询单订单归因需另补源。'],['备货与入仓','库存备货计划与入仓管理','可复用计划状态；采购金额与实收率不能由计划替代。'],['库存','公司库存与销量需求','最新快照，不随所选销售期间回溯或按店铺硬摊。'],['财报','最近完整月财报','独立月范围；不按经营日筛选拆分。']].map(([n,s,d])=>`<div class="source-row"><div><strong>${n}</strong><span class="small muted">${s}</span></div><p>${d}</p></div>`).join('')}<p class="card-note">这版只改变预览的信息层级和交互；没有向正式系统新增数据、权限或业务流程。</p>`);}
function customize(){open('自定义看板',`<p class="muted small">选择首页要显示的内容；仅保存本预览的展示偏好。</p><div class="settings-section">${sections.map(([id,label])=>`<div class="setting-row"><label for="section-${id}">${label}</label><input type="checkbox" id="section-${id}" data-section-toggle="${id}" ${visible(id)?'checked':''}></div>`).join('')}</div>${action('reset-layout','恢复精简布局','','control-btn')}`);}
function filter(){open('经营范围',`<p class="muted small">平台、店铺筛选影响年/月目标、销售、店铺异常、类目、商品与推广。库存、待办、备货计划和完整月财报保持各自范围。</p><div class="filter-form"><label>平台<select id="filter-platform" aria-label="平台"><option value="">全部平台</option>${[...new Set(shops.map(s=>s.platform))].map(p=>`<option value="${esc(p)}" ${state.platform===p?'selected':''}>${esc(p)}</option>`).join('')}</select></label><label>店铺<select id="filter-shop" aria-label="店铺">${shopOptions(state.platform,state.shop)}</select></label></div><div class="dialog-actions">${action('reset-filters','清除条件','','control-btn')}${action('apply-filter','应用筛选','','primary-btn')}</div>`);}
function shopOptions(platform,selected){return `<option value="">全部店铺</option>${shops.filter(s=>!platform||s.platform===platform).map(s=>`<option value="${s.id}" ${selected===s.id?'selected':''}>${esc(compact(s))}</option>`).join('')}`;}
function toast(msg){const el=document.querySelector('#toast');el.textContent=msg;el.classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('visible'),2200);}
function onAction(a,v){switch(a){
 case 'home':window.scrollTo({top:0,behavior:'smooth'});break;
 case 'period':set({period:v,...getRange(v)});break;
 case 'date':window.comparisonDatePicker.open({label:'自定义经营周期',startDate:model.range.start,endDate:model.range.end,minDate:'2026-01-01',maxDate:AS_OF,calendarToday:TODAY,maxDays:92,onApply:(start,end)=>set({period:'custom',start,end})});break;
 case 'todo-scope':set({mine:v==='mine'});break;
 case 'metric':set({metric:v});break;
 case 'grain':set({grain:v});break;
 case 'point':chartPoint=v;render();break;
 case 'detail':detail(v);break;
 case 'shop':shopDetail(v);break;
 case 'product':{const p=model.products.find(x=>x.id===v);if(p)open(esc(p.name),`${sourceIntro()}${detailMetric('所属品类',esc(p.category))}${detailMetric('净销售额',money(p.sales))}${detailMetric('综合大毛利',money(p.profit))}${detailMetric('大毛利率',pct(p.margin))}${table(['仓库','库存件数','可售天数'],model.inventory.items.filter(i=>i.id===p.id).map(i=>[esc(i.warehouse),num(i.qty),i.noSales?'近30日无销量':!i.matched?'未匹配':i.days==null?'不可计算':num(i.days,1)]))}<p class="card-note">销售为所选经营期间；库存为 ${model.inventory.snapshot} 的公司快照。</p>`);break;}
 case 'todo':{const view=panels().detail('todoGroup',v);open(view.title,view.body);}break;
 case 'category':{const view=panels().detail('category',v);open(view.title,view.body);}break;
 case 'gd-risk':{const view=panels().detail('guangdong',v);open(view.title,view.body);}break;
 case 'shop-mode':set({shopMode:v});break;
 case 'flow-dimension':set({flowDimension:v});break;
 case 'flow-platform':set({flowPlatform:v,flowShop:'',flowDimension:'shop'});break;
 case 'flow-shop':{const shop=model.flow.members.find(row=>row.id===v);if(shop)set({flowShop:v,flowPlatform:shop.platform,flowDimension:'shop'});}break;
 case 'flow-reset':set({flowPlatform:'',flowShop:''});break;
 case 'stock-bucket':{const b=model.inventory.buckets[Number(v)];if(b)open('库存分布 · '+esc(b.label),`${sourceIntro()}${detailMetric('快照日期',model.inventory.snapshot)}${detailMetric('分档货值',money(b.value))}${detailMetric('占库存总货值',pct(ratio(b.value,model.inventory.value)))}<p class="card-note">分档互斥，不把销量未匹配当作无销量。查看完整清单可回到库存健康详情。</p>${action('detail','查看完整库存','inventory','control-btn')}`);break;}
 case 'help':open(esc(v)+' · 指标说明',`<p>${definitions[v]||'按标注来源与期间统计，空值不当作零。'}</p>`);break;
 case 'filter':filter();break;
 case 'apply-filter':{const platform=dialog.querySelector('#filter-platform').value,shop=dialog.querySelector('#filter-shop').value;close();set({platform,shop});break;}
 case 'reset-filters':close();set({platform:'',shop:''});break;
 case 'clear-filter':set({platform:'',shop:''});break;
 case 'customize':customize();break;
 case 'reset-layout':set({hidden:[...initial.hidden]});customize();break;
 case 'more':open('更多经营信息',`<p class="small muted">首页聚焦年/月目标、运营事务、销售、店铺下滑、类目与库存。以下信息按需查看，也可通过自定义看板固定到首页。</p><div class="more-stack">${customerCard()}${supplyCard()}${productsCard()}${promotionCard()}${financeCard()}</div>`);break;
 case 'sources':sources();break;
 case 'scenario':open('演示设置',`<p>示例日期固定为 ${TODAY}，经营数据截止 ${AS_OF}。用于比较版式，不读取正式业务数据。</p><div class="filter-form"><label>数据情景<select id="scenario-select" aria-label="数据情景"><option value="normal">正常经营</option><option value="missing">平台来源缺失</option><option value="empty">选期无数据</option></select></label></div><p class="card-note">月目标保留，ERP实际缺失时不计算完成率；库存、备货和完整月财报继续展示各自来源。</p>`);dialog.querySelector('#scenario-select').value=state.scenario;break;
 case 'about':open('这一版调整了什么',`<p>参考你打开的特睿思 BI，把首页改为每天可以直接查看的经营看板。</p><ul><li>年/月目标和运营逾期、临期、周无进展事项放在最上方。</li><li>销售增加客单价，右侧直接查看店铺同比下滑。</li><li>各类目按吉客云货品分类展示净销售同比环比；库存增加广东仓异常，下面补充流量转化。</li><li>商品、推广、月财报保留为补充卡片，可自行隐藏。</li><li>去掉五案切换和大段首页说明，详细口径放进抽屉。</li></ul><p class="card-note">保留系统绿色与字体。原五套 Demo 完整保留；本版为已确认设计预览，正式数据接线和生产采用待实施。</p><a href="./ANALYSIS.md" target="_blank" rel="noopener">查看内容分析与来源映射</a>`);break;
 case 'module':{const map={'网店分析':'shopPerformance','销售分析':'sales','客服分析':'customer','商品经营':'products','库存管理':'inventory','运营事务':'todos'};if(map[v])detail(map[v]);else sources();break;}
 case 'close':close();break;
}}
document.addEventListener('click',e=>{const button=e.target.closest('[data-action]');if(button)onAction(button.dataset.action,button.dataset.value||'');});
document.addEventListener('change',event=>{const field=event.target.dataset.flowField;if(!field)return;if(field==='platform')set({flowPlatform:event.target.value,flowShop:''});else{const shop=model.flow.shopOptions.find(row=>row.id===event.target.value);set({flowShop:shop?.id||'',flowPlatform:shop?.platform||model.flow.selection.platform});}root.querySelector('[data-flow-field="'+field+'"]')?.focus({preventScroll:true});});
document.addEventListener('keydown',e=>{if(e.target.matches('svg [role=button]')&&['Enter',' '].includes(e.key)){e.preventDefault();onAction(e.target.dataset.action,e.target.dataset.value);}});
dialog.addEventListener('change',e=>{if(e.target.id==='filter-platform')dialog.querySelector('#filter-shop').innerHTML=shopOptions(e.target.value,'');if(e.target.dataset.sectionToggle){const key=e.target.dataset.sectionToggle;set({hidden:e.target.checked?state.hidden.filter(x=>x!==key):[...new Set([...state.hidden,key])]});}if(e.target.id==='scenario-select'){set({scenario:e.target.value});toast('已切换演示数据情景');}});
dialog.addEventListener('click',e=>{if(e.target===dialog){const b=dialog.getBoundingClientRect();if(e.clientX<b.left)close();}});
dialog.addEventListener('close',()=>{if(returnFocus?.isConnected)returnFocus.focus();});
render();

let resizeTimer;window.addEventListener('resize',()=>{clearTimeout(resizeTimer);resizeTimer=setTimeout(()=>{const el=root.querySelector('.trend-render');if(el)el.innerHTML=chart(el.clientWidth);},100);});
